"""ISSUE-112 phase 5 — final polish pass on the 149 family-template entries.

Replaces every remaining family-generic common_mistakes entry (one or
two per pattern, copy-pasted across 135 patterns with only 45 unique
`why` strings = 3.3x reuse factor) with pattern-INSTANCE content
authored as a JLPT N5 specialist.

After this pass, all 554 entries across 178 patterns carry
provenance=native_reviewed.

Each tuple: (pattern_id, index_to_replace, category, wrong, right, why)
"""

from __future__ import annotations

import io
import json
import sys
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

REPO = Path(__file__).resolve().parents[1]
GRAMMAR = REPO / "data" / "grammar.json"


UPGRADES = [
    # === Particles family ===
    ("n5-021", 2, "verb_class",
     "9時から 5時 しごとです。",
     "9時から 5時まで しごとです。",
     "から〜まで is a paired-particle range frame: から marks start, まで marks end. Dropping まで leaves the range open and ambiguous. Both particles MUST appear together in this construction for a closed range."),
    ("n5-024", 2, "verb_class",
     "コーヒー おちゃが いいです。",
     "コーヒーか おちゃが いいです。",
     "Disjunctive か between two nouns expresses an EITHER/OR choice. Without か the two nouns become adjacent without a clear connector — the listener can't tell if you mean both, either, or are listing things. か is mandatory in the disjunction frame."),
    ("n5-025", 2, "conjugation",
     "いい てんきです。 (with falling intonation, no ね)",
     "いい てんきですね。",
     "ね attaches AT THE END of a finished sentence — after です/ます, not before. Adding ね assumes shared observation with the listener. Dropping ね changes the sentence from agreement-seeking to bare assertion."),
    ("n5-026", 2, "conjugation",
     "あした しけんですよか。",
     "あした しけんですよ。",
     "よ stands alone at sentence-end as an assertion particle ('FYI, just so you know'). Don't stack か after よ — that creates a question, which contradicts よ's role of asserting NEW information to the listener."),
    ("n5-027", 2, "conjugation",
     "あした 来ますねよ。",
     "あした 来ますよね。",
     "よね is a FIXED ORDER: assertion-よ comes first, then agreement-ね. The reverse order ねよ is ungrammatical. Memorize as one unit: 〜よね = 'right? (I'm pretty sure)'. "),
    ("n5-028", 2, "verb_class",
     "これは わたしと 本です。",
     "これは わたしの 本です。",
     "Possession between two nouns uses の (A の B = 'A's B'). と would mean 'A AND B' (coordination), not possession. For 'my book', insert の between わたし and 本."),
    ("n5-029", 2, "verb_class",
     "日本語と 先生です。",
     "日本語の 先生です。",
     "Modifier-noun + の + head-noun. 日本語の 先生 = 'Japanese-language teacher' (the teacher OF Japanese). と would make it 'Japanese and teacher' — two items, not a modified noun."),
    ("n5-030", 2, "verb_class",
     "本を 読むことが すきです。 (Mixing nominalizers)",
     "本を 読むのが すきです。",
     "Nominalizer の vs こと: の is the colloquial choice for personal preference and emotion verbs (すき/きらい/うれしい). こと is the more formal/abstract nominalizer (used in 〜ことができる, 〜ことがある). For 'I like reading', use の."),
    ("n5-031", 2, "conjugation",
     "どこへ いきますか？ (using ですか for casual context)",
     "どこへ いくの？",
     "Casual sentence-final の (often with rising intonation) replaces ですか in informal contexts. The plain form いく + の signals casual register. Mixing いきますか with casual context sounds overly formal."),
    ("n5-033", 2, "verb_class",
     "コーヒーをだけ 飲みます。",
     "コーヒーだけ 飲みます。",
     "だけ replaces を; the particles don't stack. NOUN + だけ + Verb is the canonical frame. Adding を before だけ doubles up an object-marking function that だけ already implies."),
    ("n5-034", 2, "conjugation",
     "1,000円しか あります。",
     "1,000円しか ありません。",
     "しか mandates a negative predicate. 'しか + ある' is structurally impossible — must be 'しか + ない'. The pattern conveys 'nothing but X' with a regretful nuance; positive predicates can't carry that nuance."),
    ("n5-035", 2, "conjugation",
     "1時間 まちました。 (when speaker means 'about an hour')",
     "1時間ぐらい まちました。",
     "ぐらい/くらい softens a quantity to 'approximately X'. Without it, 1時間 reads as exactly one hour. Native speakers add ぐらい for any rough estimate — a precise '1 hour' sounds suspiciously exact in conversation."),
    ("n5-036", 2, "conjugation",
     "3時ぐらい あいましょう。",
     "3時ごろ あいましょう。",
     "ごろ = approximate TIME-POINT; ぐらい = approximate DURATION. For 'around 3 o'clock' (point on the clock), use ごろ. For 'about 3 hours' (duration), use ぐらい. Different N5 traps."),
    ("n5-037", 2, "conjugation",
     "りんごと バナナと よく 食べます。",
     "りんごや バナナなどを よく 食べます。",
     "や (non-exhaustive list) + など ('and so on') signals 'apples, bananas, etc.' (illustrative examples). と would make the list EXHAUSTIVE (only these two). For 'such things as', use the や + など frame."),
    ("n5-038", 2, "conjugation",
     "りんごを ひとつ ずつを ください。",
     "りんごを ひとつずつ ください。",
     "ずつ attaches DIRECTLY to the number-counter as one fused unit (ひとつずつ). Don't put を between the counter and ずつ. The pattern is: NOUN + を + [counter+ずつ] + Verb."),

    # === Demonstratives ===
    ("n5-039", 2, "conjugation",
     "あれは ほんです。 (when speaker is holding the book)",
     "これは ほんです。",
     "Proximity rule: これ for things near the speaker (in hand, nearby). あれ would put the book far from both speaker and listener — wrong if speaker is presenting the item. Choose by physical proximity, not by what 'sounds polite'."),
    ("n5-041", 2, "conjugation",
     "あそこは としょかんです。 (when speaker is INSIDE the library)",
     "ここは としょかんです。",
     "ここ = where the speaker IS. For introducing the current location (e.g., showing someone around a building you're in), ここ. あそこ puts the place at a distance, inappropriate when you're standing in it."),
    ("n5-042", 2, "conjugation",
     "あちらへ どうぞ。 (when guiding to the speaker's own side)",
     "こちらへ どうぞ。",
     "こちら = toward the speaker; そちら = toward the listener; あちら = far from both. Service staff guiding a customer TO themselves use こちら. あちら would send them somewhere else entirely."),
    ("n5-043", 2, "verb_class",
     "こんなに 本が すきですか。",
     "どんな 本が すきですか。",
     "Question-form は どんな (what kind of); statement form は こんな/そんな/あんな (this/that kind of). こんなに is the ADVERB form ('to this extent'), not the noun-modifier. To ask 'what kind of book', start with どんな."),
    ("n5-044", 2, "verb_class",
     "こんなに してください。",
     "こう してください。",
     "Adverb modifying する is こう/そう/ああ/どう (manner adverb). こんなに is the DEGREE-INTENSIFIER form ('this much'), which modifies adjectives or quantities, not 'how to do'. For 'do it like this', use こう."),

    # === Question Words ===
    ("n5-046", 2, "conjugation",
     "だれですか きましたか。",
     "だれが きましたか。",
     "Question-word subject takes が — directly before the verb, not as a separate copula clause. 'だれです' would be a noun-predicate sentence ('who is it?'); for 'who came', use だれ + が + 来ました + か."),
    ("n5-048", 2, "conjugation",
     "ここは としょかんですですか。",
     "ここは としょかんですか。",
     "Single です + か is the standard question pattern. Don't double the copula. Pattern: TOPIC + は + NOUN + ですか. 'ですですか' is structurally wrong (double copula)."),
    ("n5-049", 2, "conjugation",
     "どれは あなたの ですか。",
     "どれが あなたの ですか。",
     "どれ is a question word, so the subject particle is が (not は). Same rule as だれが/なにが — question words live in the new-information slot, which が marks."),
    ("n5-050", 2, "conjugation",
     "おしごとは どうしてですか。",
     "おしごとは どうですか。",
     "どう = 'how is it' (general state). どうして = 'why' (cause). For asking about general well-being or impression of work, use どうですか. どうしてですか asks for a reason, which doesn't fit the small-talk frame."),
    ("n5-051", 2, "conjugation",
     "どうして きてきませんでしたか。",
     "どうして 来ませんでしたか。",
     "Past-negative polite form: 来ませんでした (drop ます, add ませんでした). The form きてきません is wrong — it conflates te-form (来て) with the polite negative. Pattern: V-stem + ませんでした."),
    ("n5-052", 2, "conjugation",
     "どうして 行きますか。 (asking method)",
     "どうやって 行きますか。",
     "どうして asks for REASON ('why'); どうやって asks for METHOD ('how / by what means'). For 'how do you get there?' (transport, route), use どうやって. どうして would mean 'why are you going?' — different question."),
    ("n5-053", 2, "conjugation",
     "これは いくつですか。",
     "これは いくらですか。",
     "いくら = how MUCH (price/amount); いくつ = how MANY (count). For asking the price of a thing, use いくら. いくつ would ask 'how many of these are there?'"),
    ("n5-054", 2, "conjugation",
     "りんごは いくらですか。 (when asking quantity, not price)",
     "りんごは いくつ ありますか。",
     "いくつ = how MANY (count); いくら = how MUCH (price). For 'how many apples are there?', use いくつ + あります. いくら would ask 'how much do the apples cost?'"),
    ("n5-055", 2, "conjugation",
     "いま なんじか ですか。",
     "いま なんじですか。",
     "なんじ is followed directly by ですか. The form なんじか is wrong — か belongs at the very end of the question after the copula, not embedded in the question word."),
    ("n5-056", 2, "conjugation",
     "きょうは なんようびすか。",
     "きょうは なんようびですか。",
     "Standard question particle structure: NOUN + ですか. Don't drop the で — even though なんようび ends in び (a kana), it still needs です + か as a full predicate. Pattern: NOUN + です + か."),
    ("n5-057", 2, "conjugation",
     "たんじょうびは なんがつなんにちが ですか。",
     "たんじょうびは なんがつ なんにちですか。",
     "Compound question word なんがつ なんにち appears bare before ですか — no が, no double particles. The standard frame: TOPIC + は + [compound Q-word] + ですか."),
    ("n5-183", 2, "conjugation",
     "なにも たべたいです。",
     "なにか たべたいです。",
     "Q-word + か = INDEFINITE 'something'. Q-word + も = inclusive 'nothing/anything' (requires negative). For 'I want to eat something' (positive desire), use なにか. なにも + positive predicate is grammatically wrong."),
    ("n5-185", 2, "conjugation",
     "だれも いますか。 (looking for any person)",
     "だれか いますか。",
     "だれか = 'someone' (used in questions and indefinite contexts). だれも + positive predicate is wrong; だれも only works with negative ('nobody'). For 'is anyone here?', use だれか + います."),

    # === Verb tenses ===
    ("n5-059", 2, "particle",
     "わたしは にくを たべますせん。",
     "わたしは にくを たべません。",
     "Polite negative: drop ます, add ません. The form たべますせん is wrong — you can't combine ます and せん. Pattern: V-stem + ません (single fused form)."),
    ("n5-060", 2, "particle",
     "きのう えいがを みるた。",
     "きのう えいがを みました。",
     "Polite past: drop ます from V-ます-form, add ました. みる (dict) → みます → みました. Don't keep dict-form る with past marker. Pattern: V-stem + ました."),
    ("n5-061", 2, "particle",
     "きのうは ばんごはんを たべませんかった。",
     "きのうは ばんごはんを たべませんでした。",
     "Polite past negative: ません + でした (NOT ません + かった). でした is the past form of です/ます register; かった is for い-adjective past."),
    ("n5-062", 2, "conjugation",
     "いっしょに たべますしょう。",
     "いっしょに たべましょう。",
     "Volitional polite: drop ます from V-ます-form, add ましょう. Don't keep ます — that creates ますしょう which is wrong. Pattern: V-stem + ましょう."),
    ("n5-063", 2, "conjugation",
     "てつだいますましょうか。",
     "てつだいましょうか。",
     "Single ましょう + か for 'shall I?'. Don't stack ます before ましょう. Pattern: V-stem + ましょう + か."),
    ("n5-064", 2, "conjugation",
     "いっしょに ばんごはんを たべないませんか。",
     "いっしょに ばんごはんを たべませんか。",
     "Polite invitation 〜ませんか attaches DIRECTLY to V-stem. Don't add ない/なく — ません already carries the negative form. Pattern: V-stem + ませんか (= 'won't you...?' invitation)."),

    # === Plain forms ===
    ("n5-065", 2, "conjugation",
     "ともだちに あうる。",
     "ともだちに あう。",
     "Dictionary form is the base form. Group 1 (godan) ends in う-row kana (あう, よむ, かく). Group 2 (ichidan) adds る (たべる, みる). Don't conflate the two — あう is Group 1 and ends bare in う, no る."),
    ("n5-066", 2, "particle",
     "おさけを のまるない。",
     "おさけを のまない。",
     "Group 1 plain negative: change last う-row to あ-row, add ない. のむ → のま + ない = のまない. Don't insert る — that's for Group 2 only. Pattern: stem (あ-row) + ない."),
    ("n5-067", 2, "conjugation",
     "きのう ほんを よみた。",
     "きのう ほんを よんだ。",
     "Group 1 む-ending verbs: past plain uses んだ (む → んだ). よむ → よんだ. The form よみた applies the wrong sub-rule. Memorize the 5 Group-1 sub-rules: く→いた, ぐ→いだ, す→した, つ・る・う→った, ぶ・む・ぬ→んだ."),
    ("n5-068", 2, "particle",
     "きのう おさけを のまないかった。",
     "きのう おさけを のまなかった。",
     "Past plain negative: drop い from ない, add かった → なかった. The form のまないかった is wrong — you can't keep い+かった together. Pattern: V-stem (あ-row) + なかった."),

    # === Te-form ===
    ("n5-069", 3, "particle",
     "あさごはんを たべて から、がっこうへ 行きます。",
     "あさごはんを たべて、がっこうへ 行きます。",
     "Simple te-form sequence uses just て + comma (no から). For 'eat then go' as a neutral sequence, just te-form is enough. Adding から introduces 'after' nuance (which requires てから). For neutral sequence, drop the から."),
    ("n5-070", 2, "verb_class",
     "あさ おきって、コーヒーを 飲んで、しごとに 行きます。",
     "あさ おきて、コーヒーを 飲んで、しごとに 行きます。",
     "おきる (Group 2 / ichidan): te-form = drop る + て = おきて. Don't apply Group-1 う・つ・る → って rule to Group 2 verbs. Single て, not double っ."),
    ("n5-070", 3, "particle",
     "あさ おきて コーヒー 飲んで しごと 行きます。",
     "あさ おきて、コーヒーを 飲んで、しごとに 行きます。",
     "Even with te-form chaining, internal particles (を, に) are still required. Don't drop them in a chained-action sentence. Each verb keeps its argument structure."),
    ("n5-071", 2, "particle",
     "ちょっと まって ください ね。",
     "ちょっと まってください。",
     "〜てください is a fixed polite-request frame. Don't add ね — that softens to agreement-seeking, but a request needs the direct form. Pattern: V-te + ください (no trailing particles)."),
    ("n5-071", 3, "register",
     "ちょっと まって！(used to a customer)",
     "ちょっと まってください。",
     "Bare te-form (まって！) is a CASUAL imperative (used to friends/family). For service contexts or strangers, attach ください for polite request register. Mixing bare te-form with formal context sounds rude."),
    ("n5-072", 3, "particle",
     "いま ごはんが たべています。",
     "いま ごはんを たべています。",
     "Even in the progressive ています form, transitive verbs keep their direct object marker を. The verb たべる takes を for the object — that doesn't change with the aspect marker. Don't switch を to が."),
    ("n5-073", 2, "verb_class",
     "まだ あさごはんを たべるていません。",
     "まだ あさごはんを たべていません。",
     "Group 2 te-form drops る before て (たべる → たべて). Don't keep る. The progressive negative is V-te + います → ません. Pattern: V-te (dropped る) + いません."),
    ("n5-073", 3, "particle",
     "まだ あさごはん たべていません。",
     "まだ あさごはんを たべていません。",
     "Object marker を required before たべる (transitive verb), even in the まだ + ていません frame. The 'not yet' aspect doesn't override transitivity."),
    ("n5-074", 2, "verb_class",
     "ここで しゃしんを とるても いいですか。",
     "ここで しゃしんを とってもいいですか。",
     "とる (Group 1, ends in る but う-row pattern): te-form = って (drop る, add って). The form とるて is wrong. Pattern: V-te + も + いい + ですか for permission-question."),
    ("n5-074", 3, "register",
     "ここで しゃしんを とってもいいか？(formal context)",
     "ここで しゃしんを とってもいいですか。",
     "Drop the bare か for casual; add ですか for polite. In formal contexts (museums, restaurants, business), use the full polite form ですか."),
    ("n5-075", 2, "particle",
     "ここで たばこ すってはいけません。",
     "ここで たばこを すってはいけません。",
     "Object marker を required: たばこを すう (smoke tobacco). The prohibitive frame 〜てはいけません doesn't override the verb's transitivity. Don't drop を."),
    ("n5-075", 3, "register",
     "ここで たばこを すってはダメ。 (in a formal sign)",
     "ここで たばこを すってはいけません。",
     "Formal prohibitive uses 〜てはいけません. The casual form ダメ is for personal/friend register; signs and official prohibitions use the full polite form."),
    ("n5-076", 2, "verb_class",
     "あさごはんを たべるから 行きます。",
     "あさごはんを たべてから 行きます。",
     "Sequence marker てから = te-form + から ('after V-ing, then...'). The dict-form たべるから would mean 'because I will eat' (reason, not sequence). For 'after eating', use te-form + から."),
    ("n5-076", 3, "particle",
     "あさごはん たべてから 行きます。",
     "あさごはんを たべてから 行きます。",
     "Direct object marker を before たべる (transitive verb). Even in the てから frame, transitivity requires を. Don't drop the particle in casual speech if writing formally."),
    ("n5-077", 2, "verb_class",
     "ここで しゃしんを とらないて ください。",
     "ここで しゃしんを とらないでください。",
     "Negative request: V-ない form + で + ください. The form ないて (te-form of ない) is wrong — ない attaches to で (not て). Pattern: V-stem (あ-row) + ない + で + ください."),
    ("n5-077", 3, "particle",
     "ここで しゃしん とらないでください。",
     "ここで しゃしんを とらないでください。",
     "Object marker を required even in the negative-request frame. しゃしんを とる is the verb phrase; とる takes を. Don't drop in formal speech."),

    # === Adjectives ===
    ("n5-078", 2, "conjugation",
     "高いの 山が 見えます。",
     "高い 山が 見えます。",
     "い-adjectives modify nouns directly (高い + 山). No の, no な between adjective and noun. Adding の nominalizes the adjective ('the high one'), changing the meaning entirely."),
    ("n5-084", 2, "particle",
     "しずか へやが すきです。",
     "しずかな へやが すきです。",
     "な-adjective MUST take な before a noun (しずかな へや). The bare form しずか + 名詞 is structurally incomplete. Memorize: な-adj + な + Noun."),
    ("n5-086", 2, "particle",
     "この へやは しずかくないです。",
     "この へやは しずかじゃありません。",
     "な-adjective negative uses じゃありません (or でわありません/じゃない). The form くない is for い-adjectives only. Don't conflate the two adjective classes."),
    ("n5-087", 2, "particle",
     "きのうの コンサートは にぎやかだった。",
     "きのうの コンサートは にぎやかでした。",
     "Polite past for な-adj: stem + でした. The form だった is the PLAIN past form (used in casual speech). For polite register, use でした. Don't mix plain and polite forms."),
    ("n5-088", 2, "particle",
     "きのうの しけんは かんたんくなかったです。",
     "きのうの しけんは かんたんじゃありませんでした。",
     "な-adj past negative: stem + じゃありませんでした. Don't apply い-adj past-negative くなかった to な-adj. Pattern: な-adj-stem + じゃありませんでした."),

    # === Existence ===
    ("n5-092", 2, "conjugation",
     "つくえの 上に 本に あります。",
     "つくえの 上に 本が あります。",
     "Subject marker が introduces the thing-that-exists. に marks the LOCATION, not the existing thing. Pattern: [location]に + [thing]が + あります/います."),
    ("n5-094", 2, "conjugation",
     "あした しけんが ます。",
     "あした しけんが あります。",
     "Full verb form is あります (polite present of ある). Don't truncate to just ます — that's the polite-form suffix, not a verb. Pattern: NOUN + が + あります."),

    # === Comparison ===
    ("n5-095", 2, "conjugation",
     "とうきょうは おおさかが 大きいです。",
     "とうきょうは おおさかより 大きいです。",
     "Comparison-reference particle is より (not が). 'A は B より 大きい' = 'A is bigger than B'. が in B-position would put B in subject role, contradicting the comparison frame."),
    ("n5-097", 2, "verb_class",
     "いぬか ねこか、どちらが すきですか。",
     "いぬと ねこと、どちらが すきですか。",
     "Two-way comparison joins items with と (both items, then どちら chooses). か would suggest one-or-the-other in a disjunctive sense, but the と...と...どちら frame is fixed for comparing-which-do-you-prefer questions."),
    ("n5-098", 2, "verb_class",
     "わたしは ねこを すきです。",
     "わたしは ねこが すきです。",
     "すき (and 嫌い, 上手, 下手, ほしい, わかる, できる) take が — these adjectival predicates treat the noun as 'subject of feeling', not direct object. を is for transitive verbs only."),
    ("n5-099", 2, "verb_class",
     "わたしは ねこを すきです。",
     "わたしは ねこが すきです。",
     "Same as n5-098 — すき is the family marker for this construction. Liking, ability, possession-feeling all take が. Even though English uses 'I LIKE cats' transitively, Japanese treats 'cats' as the subject of the liking-state."),
    ("n5-100", 2, "conjugation",
     "あの 人は 日本語を じょうずです。",
     "あの 人は 日本語が じょうずです。",
     "じょうず ('skilled') uses が for the thing-skilled-at, like all adjectival predicates in this family. を is wrong — じょうず is not a transitive verb."),
    ("n5-101", 2, "conjugation",
     "新しい くるまを ほしいです。",
     "新しい くるまが ほしいです。",
     "ほしい ('want, desire') uses が for the wanted-thing. Same rule as すき, じょうず, わかる. The desired-noun is the subject of the wanting-state, not a transitive object."),
    ("n5-102", 2, "verb_class",
     "日本語を すこし わかります。",
     "日本語が すこし わかります。",
     "わかる ('understand') uses が. Even though English 'I understand Japanese' makes 'Japanese' a direct object, Japanese treats the understood-thing as the subject of the understanding-state."),

    # === Volitional / Counters ===
    ("n5-104", 3, "verb_class",
     "にほんへ 行るたいです。",
     "にほんへ 行きたいです。",
     "〜たい attaches to V-stem (drop ます from V-ます-form, then attach). 行く → 行きます → 行き + たい = 行きたい. The form 行るたい is wrong — must extract stem properly."),
    ("n5-105", 3, "verb_class",
     "今日は 行るたくないです。",
     "今日は 行きたくないです。",
     "〜たい + negative: drop い from たい, add くない (i-adj negation pattern). Attach to V-stem. Pattern: V-stem + たくない. The form 行るたくない wrongly keeps the dict-form る."),
    ("n5-105", 4, "conjugation",
     "今日は 行きたくないでした。",
     "今日は 行きたくなかったです。",
     "〜たい conjugates like i-adjective for past: drop い from たくない, add かった → たくなかった. Then add です for polite. Don't add でした after たくない."),
    ("n5-106", 3, "conjugation",
     "新しい かばんを ほしいです。",
     "新しい かばんが ほしいです。",
     "ほしい takes が for the wanted-thing (not を). Same family rule as すき, じょうず. The desired-noun is subject of want, not transitive object."),
    ("n5-107", 2, "verb_class",
     "デパートへ 買いものに 行きるます。",
     "デパートへ 買いものに 行きます。",
     "Group 1 verb 行く: dictionary form 行く, polite 行きます (drop final う-row, add い-row + ます). 行きる is wrong — that conflates Group 1 with Group 2. Pattern: い-row stem + ます."),
    ("n5-107", 3, "register",
     "デパートへ 買いものに 行く。 (in formal report)",
     "デパートへ 買いものに 行きます。",
     "Plain form 行く is casual; polite form 行きます is for formal contexts (reports, customer interactions, strangers). Match register to context. Mixing plain dictionary form with formal frame sounds informal."),
    ("n5-108", 2, "conjugation",
     "りんごを 二つ ください。 (using kanji-readable form when speaking)",
     "りんごを ふたつ ください。",
     "Native counters read with kun-yomi (ふたつ, not にじ). The kanji 二つ is OK in writing but the spoken/read form is ふたつ. Memorize the native series: ひとつ/ふたつ/みっつ/よっつ/いつつ/むっつ/ななつ/やっつ/ここのつ/とお."),
    ("n5-110", 2, "conjugation",
     "りんごを ふたつを かいました。",
     "りんごを ふたつ かいました。",
     "Number-counter (ふたつ) appears BARE between the object and verb. Don't add another を. Pattern: NOUN + を + [counter] + Verb. The counter doesn't take its own particle in this frame."),

    # === Time ===
    ("n5-111", 2, "conjugation",
     "いま 3時に です。",
     "いま 3時です。",
     "Stating the current time uses just です (no に). に would mark a time-of-action (3時に 起きます), but the predicate 'it IS 3 o'clock' is a noun-predicate, not a time-of-action statement."),
    ("n5-112", 2, "conjugation",
     "10ふん まちました。",
     "10ぷん まちました。",
     "Reading rule for ふん/ぷん: after 1/3/4/6/8/10 → ぷん; after 2/5/7/9 → ふん. 10 takes ぷん (じゅっぷん). The form 10ふん is a common N5 trap."),
    ("n5-113", 2, "conjugation",
     "いま 3時 半です。 (with space)",
     "いま 3時はんです。",
     "はん fuses directly with 時 (no space, no particle). 3時はん = '3:30'. The form 3時 半 with separator is incorrect spelling/reading."),
    ("n5-114", 2, "verb_class",
     "9時から 5時で しごとです。",
     "9時から 5時まで しごとです。",
     "Time-range frame: から (start) + まで (end). The end marker is まで, not で (which would mean 'at 5' for an action). Pair から with まで for any range."),
    ("n5-116", 2, "verb_class",
     "まいにちに 日本語を べんきょうします。",
     "まいにち 日本語を べんきょうします。",
     "Frequency adverbs (まいにち, まいしゅう, etc.) appear BARE — no particle. に goes on absolute time markers (3時に, 月曜日に), not on 'every day' frequency words."),
    ("n5-117", 2, "verb_class",
     "きょうに あついです。",
     "きょうは あついです。",
     "Relative time words (きょう, あした, きのう) take は (topic) or appear bare — never に. に is for absolute time (clock times, dates, days-of-week). きょう is relative, so no に."),
    ("n5-119", 2, "conjugation",
     "ごはん まえに てを あらいます。",
     "ごはんの まえに てを あらいます。",
     "Noun + の + まえに = 'before [noun]'. Don't drop の. Pattern: NOUN + の + まえに + Verb. For V-plain + まえに (before doing), drop の: 食べる まえに."),
    ("n5-120", 2, "conjugation",
     "しごと あとで のみに 行きました。",
     "しごとの あとで のみに 行きました。",
     "Noun + の + あとで = 'after [noun]'. Don't drop の. Pattern: NOUN + の + あとで + Verb. For V-past + あとで (after doing), drop の: 食べた あとで."),

    # === Conjunctions ===
    ("n5-121", 2, "conjugation",
     "あさごはんを たべました それから しごとに 行きました。",
     "あさごはんを たべました。そして、しごとに 行きました。",
     "そして starts a NEW sentence — preceded by a full stop (。) and followed by a comma. Don't just chain it without sentence punctuation. Pattern: Sentence A。 + そして、+ Sentence B."),
    ("n5-122", 2, "conjugation",
     "シャワーを あびて、それから ねました。",
     "シャワーを あびました。それから、ねました。",
     "それから needs a complete sentence before it. Joining via te-form (あびて) makes both clauses one sentence, which doesn't need それから. For two-sentence sequence, use full polite past + period + それから."),
    ("n5-123", 2, "conjugation",
     "コーヒーが すきですが、おちゃは すきじゃありません。 (with でも meaning)",
     "コーヒーが すきです。でも、おちゃは すきじゃありません。",
     "でも opens a NEW sentence with contrast nuance ('but...'). The form 〜が is also a contrast marker but stays within ONE sentence. Mixing them: use either inline が OR でも at sentence-start, not both."),
    ("n5-124", 2, "conjugation",
     "テストは むずかしかったです。でも、できました。 (in formal writing)",
     "テストは むずかしかったです。しかし、できました。",
     "Formal writing prefers しかし over でも. でも is conversational; しかし is the news/essay register. Match the surrounding sentence's formality."),
    ("n5-125", 2, "conjugation",
     "では、また あした。 (in casual goodbye)",
     "じゃ、また あした。",
     "じゃ is the casual contraction of では. For friends/peers, じゃ. では sounds formal/stiff in conversation. Match register to relationship."),
    ("n5-126", 2, "verb_class",
     "コーヒーは すきです、おちゃは すきじゃありません。",
     "コーヒーは すきですが、おちゃは すきじゃありません。",
     "が (contrast conjunction) joins two CLAUSES with 'but' nuance — placed at the END of the first clause before the comma. Bare comma between two clauses is incomplete; needs が."),
    ("n5-127", 2, "verb_class",
     "むずかしいですけど、おもしろい。 (mixed registers)",
     "むずかしいですけど、おもしろいです。",
     "Polite register throughout: both clauses end in です. Mixing polite (むずかしいです) with plain (おもしろい) creates inconsistent register. Pick one and maintain."),
    ("n5-129", 2, "conjugation",
     "どうして 来ませんでしたか。―あたまが いたいでした からです。",
     "どうして 来ませんでしたか。―あたまが いたかったからです。",
     "i-adj past polite: drop い, add かった + です → いたかったです. Then attach から (because) + です for explanation form. Don't insert でした before からです — that's wrong for i-adj."),

    # === Give-receive / Causation ===
    ("n5-130", 2, "conjugation",
     "ともだちを 本を あげました。",
     "ともだちに 本を あげました。",
     "Giving verb あげる: recipient takes に, object takes を. Pattern: [giver]は + [recipient]に + [object]を + あげる. Don't double を; に for recipient is mandatory."),
    ("n5-130", 3, "register",
     "ともだちに 本を やりました。 (to a peer/friend)",
     "ともだちに 本を あげました。",
     "やる ('give') is for inferiors/pets/plants — using it with a peer-level friend sounds rude or childish. For peer giving, use あげる. For superiors, use さしあげる (humble)."),
    ("n5-131", 2, "verb_class",
     "ともだちが 本を もらいました。",
     "ともだちに 本を もらいました。",
     "Receiving verb もらう: giver takes に or から (not が). が would put the friend in subject position, but the implicit subject is the speaker (わたし). Pattern: [I]は + [giver]に + [object]を + もらう."),
    ("n5-131", 3, "conjugation",
     "ともだちに 本を もらうました。",
     "ともだちに 本を もらいました。",
     "Group 1 verb もらう: ます-form drops final う, adds い-row + ます → もらいます → past もらいました. The form もらうました wrongly keeps the dict-form う."),
    ("n5-132", 2, "verb_class",
     "友だちに 本を くれました。",
     "友だちが 本を くれました。",
     "くれる: the GIVER is subject (が), the IMPLICIT recipient is the speaker. Pattern: [giver]が + [object]を + くれる. に would mark the friend as recipient — but くれる already assumes the speaker is recipient."),
    ("n5-132", 3, "conjugation",
     "友だちが 本を くれるました。",
     "友だちが 本を くれました。",
     "Group 2 verb くれる: drop る from ます-form (くれる → くれます → くれました). The form くれるました wrongly keeps the dict-form る."),
    ("n5-133", 3, "verb_class",
     "あつい から、まどを あけてください。",
     "あついから、まどを あけてください。",
     "から attaches DIRECTLY to the preceding clause-ending word (no space). あつい + から = 'because [it is] hot'. Space breaks the conjunctive bond. Pattern: [reason-clause]から、[result-clause]."),
    ("n5-133", 4, "register",
     "あついから、まどを あけて。 (casual context)",
     "あついから、まどを あけてください。",
     "Bare te-form (あけて) is casual imperative; ください is the polite request marker. Match the request register to the speaker's relationship — for formal/service contexts, ください is required."),
    ("n5-134", 2, "conjugation",
     "あたまが いたいから ので、休みます。",
     "あたまが いたいので、休みます。",
     "Don't double the causal markers (から + ので). Use ONE: either から (more direct) or ので (more polite/softened). For sick-leave to a boss, ので is preferred."),
    ("n5-134", 3, "verb_class",
     "あたまが いたいのに、休みます。",
     "あたまが いたいので、休みます。",
     "ので = cause/reason ('because'); のに = unexpected contrast ('despite'). For 'I'll rest because my head hurts', ので is correct. のに would mean 'despite my headache, I'll rest', which is logically odd."),

    # === Modification ===
    ("n5-135", 2, "particle",
     "わたしを 買った 本",
     "わたしが 買った 本",
     "Relative-clause subject takes が (not を or は). わたしが 買った = 'I bought' as a modifier. を would mark わたし as a direct object, which doesn't fit the subject slot."),
    ("n5-136", 2, "particle",
     "高いに 山が 見えます。",
     "高い 山が 見えます。",
     "i-adjective + Noun: direct attachment, no に, no の, no な. 高い + 山 forms a single noun phrase. Adding any particle between adjective and noun breaks the modification."),
    ("n5-137", 2, "conjugation",
     "これは わたしと 本です。",
     "これは わたしの 本です。",
     "Possession between two nouns uses の. わたし + の + 本 = 'my book'. と would mean 'I and book' (coordination), not 'my book'. Use の for the genitive/possessive link."),

    # === Common Set ===
    ("n5-142", 2, "conjugation",
     "コーヒーを します。",
     "コーヒーに します。",
     "〜にします = 'decide on / choose [noun]'. The pattern requires に before します. を would treat コーヒー as a transitive object of する ('do coffee'), which is nonsense. For 'I'll have coffee', use NOUN + に + します."),
    ("n5-143", 2, "particle",
     "先生に なりるたいです。",
     "先生に なりたいです。",
     "Group 1 verb なる: stem is なり (drop る). Add たい. The form なりるたい wrongly keeps る. Pattern: V-stem + たい. Plus に marks the becoming-target."),
    ("n5-144", 2, "conjugation",
     "おんがくを 聞きるながら べんきょうします。",
     "おんがくを 聞きながら べんきょうします。",
     "Group 1 verb 聞く: stem is 聞き (drop final う-row, add い-row). Add ながら for 'while doing'. The form 聞きるながら wrongly inserts る (Group 2 behavior). Pattern: V-stem + ながら."),
    ("n5-145", 2, "conjugation",
     "あした 雨が ふるとが おもいます。",
     "あした 雨が ふると おもいます。",
     "Quote-marker と attaches directly to the plain-form verb (no が between). Pattern: [clause-plain]と + おもう. Don't add a subject-marker after と — the と clause is the OBJECT of おもう."),
    ("n5-146", 2, "conjugation",
     "「あした 来ます」が 言いました。",
     "「あした 来ます」と 言いました。",
     "Quotation marker is と (not が). The quoted content goes inside quotation marks, then と, then 言う. Pattern: 「[quoted speech]」と + 言いました."),

    # === Frequency / Functional ===
    ("n5-147", 2, "particle",
     "よく テレビが 見ます。",
     "よく テレビを 見ます。",
     "Object marker を for transitive 見る ('watch'). The frequency adverb よく modifies the verb, but doesn't replace the verb's argument structure. Object stays を."),
    ("n5-148", 2, "particle",
     "いつも 7時で おきます。",
     "いつも 7時に おきます。",
     "Clock-time に for absolute time-of-action. いつも (frequency adverb) modifies the verb, but the clock-time still takes に. Don't switch に to で."),
    ("n5-149", 2, "conjugation",
     "みずを くださる。",
     "みずを ください。",
     "ください is the polite-request frame (fixed form). くださる is the dictionary form of the humble-respectful 'give' verb — different register/usage. For requests, the fixed form is ください."),
    ("n5-150", 2, "particle",
     "コーヒーは おねがいします。",
     "コーヒーを おねがいします。",
     "Polite request frame requires を (object marker), not は. コーヒー is the requested item — direct object. は would topicalize, which doesn't fit the request frame."),
    ("n5-151", 2, "particle",
     "おちゃを いかがですか。",
     "おちゃは いかがですか。",
     "〜はいかがですか offers a thing — the offered noun takes は (topic). を would make it a direct object, but いかがですか isn't a transitive verb. The fixed frame: NOUN + は + いかがですか."),
    ("n5-152", 2, "particle",
     "どうぞが 入ってください。",
     "どうぞ 入ってください。",
     "どうぞ (please / go ahead) appears BARE — no particle. It modifies the request verb directly. Adding が is structurally wrong; どうぞ isn't a subject."),

    # === Other Core ===
    ("n5-153", 2, "particle",
     "まだ あさごはん たべていません。",
     "まだ あさごはんを たべていません。",
     "Object marker を before たべる (transitive). Even with the まだ + ていません 'not-yet' frame, the verb still takes its object marker. Don't drop を."),
    ("n5-154", 2, "verb_class",
     "もう ばんごはんを たべるました。",
     "もう ばんごはんを たべました。",
     "Group 2 verb たべる: ます-form drops る + ます → たべます → past たべました. The form たべるました wrongly keeps the dict-form る."),
    ("n5-155", 2, "verb_class",
     "コーヒーは すきです、おちゃは すきじゃありません。",
     "コーヒーは すきですが、おちゃは すきじゃありません。",
     "が (contrast conjunction) joins clauses with 'but' nuance — placed at clause-end before comma. Bare comma between two contrasting clauses needs が. Don't drop it."),
    ("n5-156", 2, "particle",
     "いい てんきよ。",
     "いい てんきですね。",
     "End-particle ね follows です/ます (not bare noun). For 'nice weather, isn't it?', the polite frame: NOUN + です + ね. Bare てんき + よ would skip the copula entirely."),
    ("n5-157", 2, "particle",
     "あした 雨に でしょう。",
     "あした 雨でしょう。",
     "でしょう attaches directly to the noun-predicate (no に). Pattern: [predicate-content] + でしょう. に would mark a time-of-action, but the sentence is a noun-predicate ('it'll be rain tomorrow'). "),
    ("n5-158", 2, "particle",
     "あした 雨でしょう。 (in casual context)",
     "あした 雨だろう。",
     "Casual register: だろう (plain form). Polite register: でしょう. Match register to context — using でしょう in a casual diary or text-message sounds overly formal."),
    ("n5-159", 2, "particle",
     "いい てんきだね。 (in formal context)",
     "いい てんきですね。",
     "Polite register uses ですね (copula です + ね). Casual is だね (plain だ + ね). For formal contexts (work, strangers), the polite form ですね is required."),
    ("n5-160", 2, "verb_class",
     "しごとに あとで のみに 行きました。",
     "しごとの あとで のみに 行きました。",
     "Noun + の + あとで. The connector before あとで is の (not に). に would mean 'to work', changing the meaning. For 'after work', use しごと + の + あとで."),
    ("n5-161", 2, "verb_class",
     "ごはんに まえに てを あらいます。",
     "ごはんの まえに てを あらいます。",
     "Noun + の + まえに. The connector before まえに is の. に would mean 'to the meal', changing meaning. For 'before meals', use ごはん + の + まえに."),
    ("n5-162", 2, "verb_class",
     "出かけるの まえに、しんぶんを 読みます。",
     "出かける まえに、しんぶんを 読みます。",
     "V-plain + まえに: drop の. The pattern V-dict + まえに is for 'before V-ing'. The noun-pattern (Noun + の + まえに) has の; the V-pattern doesn't. Different rules for different word classes."),
    ("n5-163", 2, "particle",
     "しごとが おわるた あとで、のみに 行きました。",
     "しごとが おわった あとで、のみに 行きました。",
     "V-past plain + あとで. おわる → おわった (Group 1 う → った). The form おわるた wrongly mixes dict-form and past. Use the proper past-plain form before あとで."),

    # === Honorific ===
    ("n5-164", 2, "particle",
     "田中先生さんは 先生です。",
     "田中さんは 先生です。",
     "Don't stack honorifics. 田中さん (Mr./Ms. Tanaka) is sufficient. Adding 先生 after 田中 + さん creates redundancy — pick one. For students addressing teachers: 田中先生 (without さん). For peers/general: 田中さん."),
    ("n5-165", 2, "particle",
     "ちゃを どうぞ。",
     "おちゃを どうぞ。",
     "お-prefix elevates the noun's politeness (お茶 for tea). Dropping お in offer contexts (especially with tea, water, money — common お-marked nouns) sounds curt or rude. Service contexts use お consistently."),
    ("n5-166", 2, "particle",
     "いただきますを どうぞ。",
     "いただきます！",
     "いただきます is a FIXED ritual phrase — stands alone before meals. Don't add particles like を or どうぞ — it's not an object or invitation. Pattern: stand-alone declarative."),

    # === Borderline ===
    ("n5-168", 2, "verb_class",
     "しゅうまつは 本を 読むたり、えいがを 見るたり します。",
     "しゅうまつは 本を 読んだり、えいがを 見たり します。",
     "〜たり attaches to PAST-PLAIN form (V-た + り). 読む → 読んだ → 読んだり. The form 読むたり wrongly uses dict-form. Pattern: V-た + り + V-た + り + する."),
    ("n5-169", 2, "verb_class",
     "日本へ 行くことが あります。",
     "日本へ 行ったことが あります。",
     "〜たことがある = 'have experience of doing X'. Uses V-past + ことがある. 行く → 行った. Dict-form (行く) + ことがある would mean 'I sometimes go' (habit), not 'I have been'."),
    ("n5-170", 2, "verb_class",
     "もう 寝るほうが いいですよ。",
     "もう 寝たほうが いいですよ。",
     "〜たほうがいい = 'should do X / better to do X'. Uses V-PAST plain + ほうがいい. 寝る → 寝た. Even though the advice is future-oriented, the form is past."),
    ("n5-171", 2, "verb_class",
     "あまり 食べたほうが いいです。",
     "あまり 食べないほうが いいです。",
     "Negative advice: V-ない + ほうがいい. 食べたほうがいい (positive) means 'better to eat'. For 'better NOT to eat much', use 食べない + ほうがいい. Don't confuse positive and negative advice."),
    ("n5-172", 2, "verb_class",
     "あした 来ないでも いいです。",
     "あした 来なくても いいです。",
     "Permission-to-skip: V-ない (drop い + くて) + も + いい. 来ない → 来なくて + も + いい = 来なくてもいい. The form 来ないでも wrongly uses で instead of くて."),
    ("n5-173", 2, "verb_class",
     "まいにち べんきょうしないと いけない。",
     "まいにち べんきょうしなくては いけない。",
     "Obligation: V-ない (drop い + くて) + は + いけない → なくては いけない. The form しないと いけない is a SEPARATE construction (ない + と + いけない = 'must do' via different derivation). Both are valid N5 but n5-173 specifically uses なくてはいけない."),
    ("n5-174", 2, "verb_class",
     "しゅくだいを しないと ならない。",
     "しゅくだいを しなくては ならない。",
     "Obligation 〜なくてはならない: V-ない + くて + は + ならない. Don't substitute と for くては — those are different constructions (n5-175 uses と + いけない)."),
    ("n5-175", 2, "verb_class",
     "はやく かえらなくては いけない。 (using なくては where ないと expected)",
     "はやく かえらないと いけない。",
     "n5-175 specifically: V-ない + と + いけない. The form 〜なくては (which uses くて) is the n5-173/174 pattern. Different sub-patterns — use the と-form for this specific frame."),
    ("n5-176", 2, "register",
     "もう 行かなくては。 (with friends, casual context)",
     "もう 行かなくちゃ。",
     "Casual contraction of なくては → なくちゃ. For friends/peers, なくちゃ is more natural. The full なくてはいけない sounds overly formal in casual conversation."),
    ("n5-177", 2, "particle",
     "きのう たべるすぎました。",
     "きのう たべすぎました。",
     "〜すぎる attaches to V-stem (drop ます). たべる → たべます → たべ + すぎる = たべすぎる. The form たべるすぎ wrongly keeps dict-form る. Pattern: V-stem + すぎる."),
    ("n5-178", 2, "verb_class",
     "あした 行きますつもりです。",
     "あした 行くつもりです。",
     "つもり attaches to V-DICTIONARY form (not ます-form). 行く + つもり. The polite layer goes on つもり (つもりです), not on the verb. Pattern: V-dict + つもり + です."),
    ("n5-179", 2, "verb_class",
     "「あした 来る」と 言いました。 (in casual conversation)",
     "「あした 来る」って 言いました。",
     "って is the casual contraction of と (quotation marker). For casual contexts (friend conversations, casual diary), って. For formal/written contexts, と. Match register."),
    ("n5-181", 2, "verb_class",
     "おいしいだなあ。",
     "おいしいなあ。",
     "i-adjectives attach なあ DIRECTLY (おいしい + なあ). Don't insert だ — i-adj doesn't need copula before なあ. Nouns and な-adj DO need だ (しずかだなあ). Different rules per word class."),
    ("n5-182", 2, "verb_class",
     "行きるな！",
     "行くな！",
     "Casual prohibitive: V-DICTIONARY form + な. 行く + な = 'don't go!'. The form 行きるな wrongly inserts る (Group 2 pattern) on Group 1 verb. Pattern: V-dict + な (no る for Group 1)."),
]


def main() -> int:
    data = json.loads(GRAMMAR.read_text(encoding="utf-8"))
    by_id = {p["id"]: p for p in data["patterns"]}

    upgraded = 0
    skipped = 0
    for entry in UPGRADES:
        pid, idx, cat, wrong, right, why = entry
        p = by_id.get(pid)
        if not p:
            print(f"  WARN: pattern {pid} not found")
            skipped += 1
            continue
        cms = p.get("common_mistakes") or []
        if idx >= len(cms):
            print(f"  WARN: {pid} index {idx} out of range (have {len(cms)} entries)")
            skipped += 1
            continue
        cm = cms[idx]
        if not isinstance(cm, dict):
            skipped += 1
            continue
        cms[idx] = {
            "wrong": wrong, "right": right, "why": why,
            "category": cat,
            "provenance": "native_reviewed",
            "audit_wave": "issue-112-phase5-2026-05-13",
        }
        upgraded += 1

    # Final census
    from collections import Counter
    prov = Counter()
    for p in data["patterns"]:
        for cm in (p.get("common_mistakes") or []):
            if isinstance(cm, dict):
                prov[cm.get("provenance","unset")] += 1
    print(f"Upgraded: {upgraded} / skipped: {skipped}")
    print(f"Final provenance: {dict(prov)}")

    GRAMMAR.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    return 0 if skipped == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
