"""IMP-004 (2026-05-14): build a denormalized per-kanji record file.

Joins three sources into one record per kanji:
  - data/n5_kanji_whitelist.json (the membership / count canonical)
  - data/n5_kanji_readings.json  (on/kun/primary readings)
  - data/kanji.json               (full metadata: examples, mnemonic,
                                   stroke order SVG path, look-alikes)

Output: data/n5_kanji_full.json — one denormalized record per kanji,
all metadata inline. The kanji-study UI can load this single file
instead of fetching + joining 3 separate files client-side (which
risked version drift between fetches).

This script is a BUILD-TIME tool. Run it any time the upstream files
change. The output file should be committed alongside the upstream
files so the runtime serves a stable, consistent join.

Run from N5/ root:
    python -X utf8 tools/build_n5_kanji_full.py
"""
import json
from collections import OrderedDict
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WL = ROOT / "data" / "n5_kanji_whitelist.json"
READINGS = ROOT / "data" / "n5_kanji_readings.json"
KANJI = ROOT / "data" / "kanji.json"
OUT = ROOT / "data" / "n5_kanji_full.json"


def main() -> int:
    whitelist = json.loads(WL.read_text(encoding="utf-8"))
    readings = json.loads(READINGS.read_text(encoding="utf-8"))
    kanji = json.loads(KANJI.read_text(encoding="utf-8"))

    # Build glyph -> kanji.json entry map
    by_glyph = {e["glyph"]: e for e in kanji.get("entries", [])}

    # Build glyph -> readings entry map (skip the _meta key)
    readings_by_glyph = {k: v for k, v in readings.items() if k != "_meta"}

    denorm = []
    missing_in_readings = []
    missing_in_kanji = []
    for glyph in whitelist:
        kanji_entry = by_glyph.get(glyph)
        readings_entry = readings_by_glyph.get(glyph)
        if not kanji_entry:
            missing_in_kanji.append(glyph)
            continue
        if not readings_entry:
            missing_in_readings.append(glyph)
            # Still emit using kanji.json data
            readings_entry = {}

        merged = OrderedDict()
        merged["glyph"] = glyph
        merged["id"] = kanji_entry.get("id")
        merged["lesson_order"] = kanji_entry.get("lesson_order")
        merged["frequency_rank"] = kanji_entry.get("frequency_rank")
        merged["stroke_count"] = kanji_entry.get("stroke_count")
        # Readings — prefer the dedicated readings file; fall back to kanji.json
        merged["on"] = readings_entry.get("on", kanji_entry.get("on", []))
        merged["kun"] = readings_entry.get("kun", kanji_entry.get("kun", []))
        merged["primary_reading"] = readings_entry.get(
            "primary",
            kanji_entry.get("primary_reading", "")
        )
        # Meanings
        merged["meanings"] = kanji_entry.get("meanings", [])
        merged["meanings_hi"] = kanji_entry.get("meanings_hi", [])
        # Visual / decomposition
        merged["radical"] = kanji_entry.get("radical")
        merged["radical_decomposition"] = kanji_entry.get("radical_decomposition")
        merged["mnemonic"] = kanji_entry.get("mnemonic", "")
        merged["lookalikes"] = kanji_entry.get("lookalikes", [])
        # Examples
        merged["examples"] = kanji_entry.get("examples", [])
        merged["sentences"] = kanji_entry.get("sentences", [])
        merged["n5_compounds"] = kanji_entry.get("n5_compounds", [])
        # Stroke-order
        merged["stroke_order_svg"] = kanji_entry.get("stroke_order_svg", "")
        merged["stroke_order_trap"] = kanji_entry.get("stroke_order_trap", "")
        # Audio
        merged["audio_yomi"] = kanji_entry.get("audio_yomi", {})
        # Review
        merged["review_status"] = kanji_entry.get("review_status")
        # Authentic references (if present)
        if "authentic_refs" in kanji_entry:
            merged["authentic_refs"] = kanji_entry["authentic_refs"]
        denorm.append(merged)

    out = OrderedDict([
        ("_meta", OrderedDict([
            ("doc", "Denormalized per-kanji record file — joins n5_kanji_whitelist.json + n5_kanji_readings.json + kanji.json into one record per kanji. Generated by tools/build_n5_kanji_full.py (IMP-004, 2026-05-14). Runtime kanji-study UI can load THIS file instead of fetching + joining the three upstream files (which risked version drift between fetches). When any of the upstream files change, re-run the build script and commit the regenerated output."),
            ("schema_version", 1),
            ("generatedAt", datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")),
            ("count", len(denorm)),
            ("sources", [
                "data/n5_kanji_whitelist.json",
                "data/n5_kanji_readings.json",
                "data/kanji.json"
            ]),
            ("regenerate_with", "python -X utf8 tools/build_n5_kanji_full.py"),
            ("see_also", [
                "data/kanji.json (canonical full metadata, single-kanji edits go HERE first)",
                "data/n5_kanji_whitelist.json (membership canonical, kept stable for downstream indexers)",
                "data/n5_kanji_readings.json (on/kun/primary readings canonical)"
            ])
        ])),
        ("entries", denorm)
    ])
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(f"Wrote {OUT.name}: {len(denorm)} denormalized kanji records")
    if missing_in_readings:
        print(f"WARN: {len(missing_in_readings)} kanji missing in readings.json: {missing_in_readings[:5]}")
    if missing_in_kanji:
        print(f"ERROR: {len(missing_in_kanji)} kanji missing in kanji.json: {missing_in_kanji[:5]}")
        return 1
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
