"""DEPRECATED 2026-05-17 — DO NOT RUN.

This is the ORIGINAL monolithic builder for
specifications/test-scenarios-by-specialist-perspective.xlsx. It was
authored when the xlsx had only 10 columns and ~240 scenarios. Since
then the xlsx has been heavily iterated:

  - 18 columns (BUG-029 + BUG-037 added 8 operational columns)
  - 402 specialist scenarios across 14 tabs (was 240 originally)
  - "User Reported Bugs" sheet (53 rows; BUG-001..053)
  - "Unit Tests (Auto-runnable)" derived sheet (111 rows)
  - Bug-class linkage updates from BUG-001..053
  - Prompt + feedback sync (b466293: +134 scenarios)
  - K-016..018 sync-drift detection scenarios (cdef185)
  - F.24 / A60 / Part 16 / etc. close-out propagation

**Running this script would OVERWRITE the live xlsx and wipe ALL
iterative additions.** Kept here in `not-required/tools-archive/` for
historical reference only. Future xlsx mutations should be done via
in-place edit scripts (tools/sync_test_scenarios_*.py, tools/fix_bugs_
*_test_scenarios_*.py, tools/build_unit_tests_sheet_*.py, tools/
add_sync_drift_scenarios_*.py — the surgical-edit pattern), never
via this whole-file rebuild.

If a from-scratch rebuild becomes necessary (e.g., schema overhaul),
re-derive from the live xlsx + this template, never run this script
unmodified.

--- ORIGINAL DOCSTRING BELOW ---

Build N5/specifications/test-scenarios-by-specialist-perspective.xlsx.

One tab per specialist-perspective category (A-N) from the 84-perspective
list. Each tab carries exhaustive test scenarios with structured columns:
ID, Sub-category, Perspective #, Scenario, Test steps, Expected result,
Priority, Severity-if-fails, Test type (manual/auto/hybrid), Notes.

Writing-discipline note: every scenario phrasing is bounded — names the
exact thing scanned/sampled, never claims universal coverage.

Run: python tools/build_test_scenarios_workbook.py
"""

import sys
sys.exit(
    "DEPRECATED 2026-05-17: this script would overwrite the live "
    "test-scenarios xlsx and wipe all iterative work (162 scenarios "
    "added across BUG-001..053 + sync batches, plus 8 added columns, "
    "User Reported Bugs sheet, Unit Tests sheet). See the deprecation "
    "header in this file. To run anyway, comment out this sys.exit()."
)
from __future__ import annotations

from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

OUTPUT = Path(__file__).resolve().parent.parent / "specifications" / \
    "test-scenarios-by-specialist-perspective.xlsx"

HEADER_FILL = PatternFill("solid", fgColor="14452A")
HEADER_FONT = Font(bold=True, color="FFFFFF", size=11)
TITLE_FONT = Font(bold=True, size=13, color="14452A")
WRAP = Alignment(wrap_text=True, vertical="top")

COLUMNS = [
    ("ID", 8),
    ("Sub-category", 22),
    ("Persp #", 8),
    ("Scenario", 56),
    ("Test steps", 60),
    ("Expected result", 50),
    ("Priority", 10),
    ("Severity if fails", 14),
    ("Test type", 14),
    ("Notes", 38),
]

# ---------------------------------------------------------------------------
# Per-category test scenarios. Each list entry:
#   (sub_category, persp_num, scenario, steps, expected, priority,
#    severity, test_type, notes)
# ---------------------------------------------------------------------------

A_JAPANESE = [
    ("Naturalness", "1", "Random-sample 200 vocab examples for native-speaker naturalness",
     "1. Random-sample 200 vocab.json examples\n2. Native teacher reads each\n3. Mark UNNATURAL / BORDERLINE / NATURAL",
     "≥98% NATURAL, 0 UNNATURAL with high confidence",
     "High", "Major", "Manual", "Coverage doc lists this as top gap; 1.3% sampled to date"),
    ("Naturalness", "1", "Random-sample 100 grammar pattern examples for register coherence",
     "1. Random-sample 100 grammar.json examples\n2. Verify register inside each example is consistent\n3. Flag mixed plain だ + polite です",
     "0 register-mixing within an example",
     "High", "Major", "Manual", "Programmatic L4 check covers across-passage; intra-example may differ"),
    ("Naturalness", "1", "Sample 50 listening scripts for cross-line register coherence",
     "1. Pull 50 listening.json items\n2. Native teacher reads full dialogue\n3. Flag unintended polite/casual switching",
     "Register changes only when narratively justified",
     "High", "Major", "Manual", "Dialogue-level not currently checked"),
    ("Naturalness", "1", "Sample 80 reading passages for paragraph-flow naturalness",
     "1. Pull all 54 reading.json passages + 26 dokkai\n2. Verify sentence-to-sentence cohesion (接続 / 指示 / 省略 use)",
     "All passages flow as a native author would write them",
     "High", "Major", "Manual", ""),
    ("Particles", "1", "は vs が discourse-choice in topic-introduction contexts",
     "1. Filter all sentences containing は OR が as topic marker (not contrast/exclusive)\n2. Verify per-context: は = known, が = new info\n3. Flag misuse",
     "0 discourse-incorrect は/が in shipped sentences",
     "High", "Major", "Manual", "Currently listed as Not Checked / requires semantic context"),
    ("Particles", "1", "に vs で disambiguation for movement vs activity locations",
     "1. Filter sentences with both に + で\n2. Verify each particle's role per verb\n3. Flag swapped usage",
     "0 swapped に/で usage",
     "High", "Major", "Manual", "AUDIT-COVERAGE flags this dimension explicitly"),
    ("Particles", "1", "を vs が with potential-form verbs (好き / できる / わかる)",
     "1. Scan all sentences with 好き / できる / わかる / ほしい\n2. Confirm particle = が",
     "All stative-adj + want-verb sentences use が",
     "High", "Critical", "Auto+Manual", "JA-88 already locks the 14 named patterns; this is the extension scan"),
    ("Conjugation", "1", "Verb-class accuracy: dictionary-form vs class tag",
     "1. For every vocab verb entry, verify pos.verb_class matches dictionary-form shape\n2. Flag mismatches (e.g., 帰る tagged ichidan)",
     "0 mis-tagged verbs",
     "High", "Critical", "Hybrid", "Subset CI-enforced; corner cases (special-ichidan-looking godan) may slip"),
    ("Conjugation", "1", "Past + negative + past-negative formation correctness across all 1009 verb entries",
     "1. Generate past/neg/past-neg programmatically per verb_class\n2. Cross-check against any example forms in entries\n3. Manual review of 50 random",
     "All inflected forms match canonical conjugation rules",
     "High", "Major", "Hybrid", ""),
    ("Conjugation", "1", "I-adj vs Na-adj conjugation in shipped examples",
     "1. Scan all adjectives + their example forms\n2. Verify い-adj uses くて/くない/かった\n3. Verify な-adj uses で/じゃない/だった",
     "0 conjugation-class violations",
     "High", "Critical", "Hybrid", "Wave-2 caught 0; broader sample could surface more"),
    ("Honorifics", "5", "尊敬語 form usage in customer/employee dialogue contexts",
     "1. Filter dialogues with role labels (店員, お客様, 先生, 学生)\n2. Verify 尊敬語 (お~になる / いらっしゃる / ご~ください) on superior's actions\n3. Verify 謙譲語 (お~する / 伺う / 申す) on inferior's actions",
     "Keigo register correct per role",
     "Medium", "Major", "Manual", "AUDIT-COVERAGE: 'Not checked / requires N3+ pragmatic analysis'"),
    ("Honorifics", "5", "Polite-prefix お / ご correctness on noun classes",
     "1. Filter all お~ / ご~ noun examples\n2. Verify お for wago (お茶, お水), ご for kango (ご飯 is exception)\n3. Flag mis-prefixed entries",
     "All お/ご prefixes follow wago/kango rules with documented exceptions",
     "Medium", "Major", "Hybrid", ""),
    ("Honorifics", "5", "Gendered sentence-final particles (わ, ぞ, ぜ) appropriateness",
     "1. Scan all dialogue lines for わ / ぞ / ぜ / わよ / だぜ\n2. Verify speaker-role tag matches gender-register convention\n3. Flag mismatches",
     "Gendered particles match speaker role",
     "Low-Medium", "Minor", "Manual", "May intentionally include stylized speech"),
    ("Counters", "7", "Counter rendaku correctness across all numeric+counter pairs",
     "1. Scan all sentences with 数字+counter\n2. Verify rendaku per phonological rules (3本=さんぼん, 6本=ろっぽん, 8本=はっぽん)\n3. Manual review of 50 random",
     "All rendaku alternants spelled correctly",
     "High", "Major", "Auto+Manual", "FP-5 documented; rendaku set may be incomplete"),
    ("Counters", "7", "Counter-noun pairing beyond the 8 canonical pairs",
     "1. Native teacher reviews 100 random counter-noun pairs\n2. Flag textbook-non-canonical pairings (e.g., 雲一個)",
     "All counter-noun pairs are textbook-canonical or documented exception",
     "Medium", "Major", "Manual", "JA-89 lock1 covers 6 caught instances; broader exists"),
    ("Counters", "7", "Native-counter (つ) range boundary (1-10)",
     "1. Filter all 〜つ examples\n2. Verify count ≤ 10 (above 10, switch to 個 or specific counter)",
     "0 instances of 11つ / 20つ etc.",
     "Medium", "Minor", "Auto", ""),
    ("Kanji", "8", "On-yomi vs kun-yomi assignment correctness",
     "1. For each of 106 kanji, verify on-yomi list matches jōyō reference\n2. Verify kun-yomi list matches jōyō reference",
     "0 misclassified readings",
     "High", "Critical", "Manual", "JA-72/76 enforce katakana-vs-hiragana convention but not the actual reading correctness"),
    ("Kanji", "8", "Stroke-count vs stroke-order data accuracy",
     "1. Cross-check each kanji's stroke-count vs Unicode CJK reference\n2. Cross-check stroke-order SVG vs KanjiVG canonical",
     "0 discrepancies",
     "Medium", "Major", "Auto", ""),
    ("Kanji", "8", "Furigana correctness in compound words",
     "1. For all compound kanji-entries, verify furigana matches the compound's actual reading (not the sum of individual readings)\n2. Spot 連濁 (rendaku in compounds): 山+川=やまかわ vs やまがわ",
     "Compound readings match canonical reference (NHK accent dict or similar)",
     "Medium", "Major", "Manual", ""),
    ("Pitch accent", "3", "Auditory verification of 944 kanjium-MATCH entries",
     "1. Native ear listens to TTS render of each\n2. Verify drop position audibly matches kanjium prediction\n3. Flag VOICEVOX-vs-NHK disagreements",
     "≥95% audible-match",
     "Medium-High", "Major", "Manual", "JA-90 narrows the gap but doesn't close it"),
    ("Pitch accent", "3", "Auditory verification of 43 low/unverified entries (16 low + 27 unverified)",
     "1. Native ear listens to TTS render of each\n2. Promote to 'high' confidence or flag for correction",
     "All 43 entries resolved",
     "High", "Major", "Manual", "Explicit gap in PITCH-ACCENT-RECONCILIATION doc"),
    ("Pitch accent", "3", "Devoiced-vowel marking on standard-Tokyo positions",
     "1. Scan vocab entries with /i/ or /u/ between voiceless consonants\n2. Verify devoicing-marker (◌̥) presence if rendered",
     "Devoicing marked where standard",
     "Low-Medium", "Minor", "Hybrid", "Not currently in data model"),
    ("Pitch accent", "3", "Multi-dialect accent variants (currently Tokyo-only)",
     "1. For high-frequency vocab, document Kansai/Kyushu alternants\n2. Decide if UI should expose them",
     "Documented; project decision recorded",
     "Low", "Minor", "Manual", "Scope decision; not a bug"),
    ("Translation", "6", "translation_en idiomatic naturalness across 6,309 sentences",
     "1. Random-sample 200 EN translations\n2. Native EN reviewer rates each NATURAL/AWKWARD/WRONG",
     "≥95% NATURAL",
     "Medium", "Major", "Manual", "74 bare-article fixed; broader pass pending"),
    ("Translation", "6", "Aspect/tense translation correctness (perfective vs imperfective)",
     "1. Filter ました vs ています examples\n2. Verify EN tense choice matches Japanese aspect",
     "0 aspect-mistranslations",
     "Medium", "Major", "Manual", ""),
    ("Translation", "6", "Article use (a/an/the/zero) in EN translations of bare-noun JA",
     "1. Filter JA sentences with bare common nouns\n2. Verify EN translation uses appropriate article (or zero article + plural)",
     "0 bare-article ungrammatical EN",
     "Medium", "Major", "Hybrid", "74 caught; checker covers 'There is X' template only"),
    ("Romaji", "9", "Hepburn vs Kunrei consistency across all romanized strings",
     "1. Scan any romaji output in data/ for し vs si, つ vs tu\n2. Pick one convention; flag drifts",
     "100% consistent within chosen convention",
     "Low-Medium", "Minor", "Auto", ""),
    ("Vocabulary scope", "2", "N5-scope vocab vs out-of-scope (N4+) contamination",
     "1. Cross-check vocab.json forms against N5 official word-list (n5_vocab_official.json)\n2. Flag entries flagged tier=n4_borderline using N5-scope kanji",
     "All tier-flags accurate; no silent N4 contamination",
     "High", "Major", "Auto+Manual", ""),
    ("Vocabulary scope", "2", "Senses-per-entry: does each vocab entry list N5-relevant sense first?",
     "1. For polysemous entries, verify sense[0] is the N5-textbook-typical sense\n2. Flag entries where rare sense leads",
     "All entries lead with N5-canonical sense",
     "Medium", "Major", "Manual", ""),
    ("Grammar scope", "2", "Grammar-pattern scope vs N5 canonical 178 patterns",
     "1. Cross-check pattern IDs against published N5 grammar list (e.g., Bunpro, Renshuu)\n2. Flag any pattern out-of-scope or missing canonical",
     "All 178 patterns are N5-canonical",
     "Medium", "Major", "Manual", ""),
]

B_JLPT_FORMAT = [
    ("Mondai structure", "11", "Mondai 1-6 distribution across paper sections per N5 spec",
     "1. Inspect papers/{bunpou,goi,moji,dokkai}\n2. Verify mondai count matches JEES N5 spec (e.g., dokkai mondai 4=10 items, mondai 5=2 items, mondai 6=1 item)",
     "Counts match JEES sample paper structure",
     "High", "Major", "Manual", "AUDIT-COVERAGE flags difficulty-calibration as unverified"),
    ("Mondai structure", "11", "Choice count per mondai (3 vs 4 vs 1)",
     "1. Filter all questions by mondai\n2. Verify choice count is JLPT-canonical\n3. Currently relaxed: mondai 3 utterance accepts both",
     "Per-mondai choice count matches spec or has documented exception",
     "Medium", "Minor", "Auto", "Already enforced as gate"),
    ("Stem format", "11", "Stem-format conformance to JLPT canonical templates",
     "1. Verify 86 of 102 papers questions match canonical stems (どこですか / 何時に / etc.)\n2. Review 16 non-template stems for justifiability",
     "All non-template stems are legitimately non-template",
     "Medium", "Minor", "Manual", "Phase C audit: 0 findings against 3 dimensions"),
    ("Distractor pedagogy", "11", "Distractor plausibility per mondai",
     "1. For 50 random mondai 1 (kanji-reading) questions, verify distractors are phonetically-near-but-wrong\n2. For 50 mondai 4 (paraphrase), verify distractors are semantically-near-but-wrong",
     "All distractors are pedagogically defensible",
     "Medium", "Major", "Manual", ""),
    ("Distractor pedagogy", "11", "Distractor-uniqueness (no duplicate distractors across questions)",
     "1. Per-paper, scan distractor pool\n2. Flag distractor reuse within paper",
     "0 within-paper duplicate distractors",
     "Low-Medium", "Minor", "Auto", ""),
    ("Difficulty calibration", "12", "Vocab-frequency against N5 official word-list",
     "1. Cross-check shipped vocab against published N5 frequency lists (Tanos / JEES sample)\n2. Flag vocab outside top-N5",
     "≥95% of shipped vocab is in N5 spec",
     "Medium", "Major", "Auto", "Reference exists but cross-validation aged"),
    ("Difficulty calibration", "12", "Grammar-pattern coverage vs JLPT-N5 official spec",
     "1. Map 178 patterns to JEES-published N5 grammar items\n2. Flag missing official patterns or extra non-spec patterns",
     "Coverage = published N5 list ± documented exceptions",
     "Medium", "Major", "Manual", ""),
    ("Difficulty calibration", "12", "Reading-passage length distribution vs real N5 dokkai",
     "1. Histogram of shipped passage character counts\n2. Compare to JEES sample dokkai (typically 60-150 chars for mondai 4, 200-300 for mondai 5)",
     "Distribution matches JEES sample",
     "Medium", "Major", "Auto", ""),
    ("Difficulty calibration", "12", "Listening-script length + speaker-count distribution",
     "1. For 50 listening items, measure script_ja chars + speaker count\n2. Compare to JEES sample N5 listening",
     "Distribution matches JEES sample",
     "Medium", "Major", "Auto", ""),
    ("Timing realism", "14", "Mock-exam time budget (105 min total for N5)",
     "1. Measure average reading speed on 5 learners' completing a full mock\n2. Verify total time ≤ 105 min",
     "Most learners finish within JLPT time budget",
     "Low-Medium", "Minor", "Manual", "Needs learner data"),
    ("Timing realism", "14", "Listening section single-play constraint",
     "1. Verify audio player disables replay on mock-exam mode\n2. Verify gap timing between items matches JEES timing",
     "Mock-mode enforces single-play",
     "Medium", "Major", "Manual", ""),
    ("Item validity", "13", "Item-difficulty p-value estimation (when learner data accumulates)",
     "1. Per-question, compute (correct learners / total attempts)\n2. Flag p > 0.95 (too easy) or p < 0.30 (too hard) for an N5 cohort",
     "p-distribution centered around 0.65-0.80",
     "Low", "Minor", "Auto", "Requires learner cohort"),
    ("Item validity", "13", "Item-discrimination (do top-scoring learners pass it?)",
     "1. Compute biserial correlation per item\n2. Flag items with correlation < 0.2",
     "All items discriminate > 0.2",
     "Low", "Minor", "Auto", "Requires learner cohort"),
    ("Format authenticity", "11", "Vocab-reading mondai format (kanji→reading vs reading→kanji)",
     "1. Verify mondai 1 = kanji→reading, mondai 2 = reading→kanji\n2. Check choice format consistency",
     "Format matches JEES",
     "Medium", "Major", "Manual", ""),
    ("Format authenticity", "11", "Kana-script consistency in mondai 3 (orthography)",
     "1. Verify mondai 3 (orthography) questions have correct-script choices in expected pattern",
     "Pattern matches JEES sample",
     "Medium", "Minor", "Manual", ""),
]

C_HINDI = [
    ("Naturalness", "15", "Random-sample 150 explanation_hi for native-speaker naturalness",
     "1. Random-sample 150 Hindi explanation strings (reading + questions + vocab)\n2. Native Hindi reviewer rates NATURAL/AWKWARD/WRONG",
     "≥95% NATURAL",
     "High", "Major", "Manual", "All 838+ Hindi entries are LLM-curated; never native-reviewed"),
    ("Naturalness", "15", "Distractor_explanations_hi clarity for learners",
     "1. Random-sample 100 distractor explanations\n2. Native Hindi reviewer rates CLEAR/CONFUSING/WRONG",
     "≥95% CLEAR",
     "High", "Major", "Manual", ""),
    ("Naturalness", "15", "rationale_hi pedagogical quality for dokkai questions",
     "1. Review all 102 dokkai rationale_hi\n2. Verify each explains why correct + why distractors are wrong",
     "All rationales pedagogically sound",
     "High", "Major", "Manual", ""),
    ("Terminology", "16", "Linguistic-term consistency: subject (कर्ता / विषय / subject)",
     "1. Grep all data/*.json for कर्ता / विषय / subject\n2. Normalize to one term per concept",
     "One canonical term per linguistic concept",
     "Medium", "Major", "Auto+Manual", "Drift likely across 12 corpora"),
    ("Terminology", "16", "Verb-class naming in Hindi (Group 1/2/3 vs godan/ichidan)",
     "1. Verify Hindi verb-class names are consistent\n2. Choose canonical Hindi term and lock",
     "All verb-class references use one Hindi term",
     "Medium", "Major", "Manual", ""),
    ("Terminology", "16", "Particle name consistency in Hindi grammar explanations",
     "1. Verify particle names (が = कर्ता-कारक vs subject-marker vs subject particle)\n2. Pick canonical",
     "Particle naming consistent across grammar.json + reading.json + questions.json",
     "Medium", "Major", "Manual", ""),
    ("Typography", "17", "Devanagari vowel-sign (matra) rendering across all browsers",
     "1. Render sample page on Chrome / Firefox / Safari / Edge\n2. Verify ि, ु, े, ो etc. attach to correct consonant",
     "0 mis-attached matras",
     "Low-Medium", "Major", "Manual", ""),
    ("Typography", "17", "Conjunct-consonant ligature rendering",
     "1. Render strings with क्ष, त्र, ज्ञ, द्ध\n2. Verify ligature forms display correctly",
     "All ligatures display as ligatures, not split",
     "Low-Medium", "Major", "Manual", ""),
    ("Typography", "17", "Font fallback when Devanagari font is missing",
     "1. Simulate user without Noto Sans Devanagari\n2. Verify graceful fallback (system Hindi font)",
     "Fallback acceptable; no tofu / boxes",
     "Low-Medium", "Minor", "Manual", ""),
    ("Typography", "17", "Mixed Devanagari + CJK + Latin baseline alignment",
     "1. Render strings combining Hindi + Japanese + English on one line\n2. Verify baselines align visually",
     "Acceptable baseline alignment",
     "Low-Medium", "Minor", "Manual", ""),
    ("Register", "18", "Formal vs informal Hindi register coherence within explanations",
     "1. Native Hindi reviewer reads each explanation_hi paragraph\n2. Flag mid-paragraph register-switching",
     "0 unintended register switches",
     "Medium", "Major", "Manual", ""),
    ("Register", "18", "Sanskritized vs Persianized vocabulary balance",
     "1. Native reviewer judges whether Hindi register is acceptable for pan-Indian audience\n2. Flag overly-Sanskritized OR overly-Urdu-leaning entries",
     "Balanced 'standard Hindi'",
     "Medium", "Minor", "Manual", ""),
    ("Register", "18", "Regional-variant neutrality (avoid Bombay / Delhi / South-India-specific idioms)",
     "1. Native reviewer scans for regionally-marked vocab\n2. Replace with pan-Indian equivalents",
     "0 regionally-marked vocab",
     "Low-Medium", "Minor", "Manual", ""),
    ("Cross-language drift", "19", "EN ↔ HI semantic equivalence on the same JA sentence",
     "1. Sample 100 sentences with explanation_en + explanation_hi\n2. Bilingual reviewer verifies meaning equivalence",
     "0 semantic drift cases",
     "Medium", "Major", "Manual", "Never cross-checked"),
    ("Cross-language drift", "19", "Hindi-version pedagogical depth = English-version pedagogical depth",
     "1. For 50 grammar-pattern explanations, verify Hindi explains as much as English",
     "Hindi-version not noticeably thinner",
     "Medium", "Major", "Manual", ""),
    ("Locale parity", "15", "Field-presence parity: every EN field has its HI counterpart",
     "1. Run JA-39 / JA-85 / JA-86 invariants\n2. Verify 0 missing HI fields",
     "0 EN-only or HI-only entries",
     "High", "Critical", "Auto", "Already CI-enforced"),
    ("Hindi UI", "15", "Hindi locale-switch state retention across navigation",
     "1. Toggle UI to HI\n2. Navigate Grammar → Vocab → Reading\n3. Verify HI persists",
     "Locale persists across routes",
     "Medium", "Major", "Manual", ""),
    ("Hindi pedagogy", "15", "Hindi explanations don't presume English knowledge",
     "1. Native Hindi-monolingual reviewer reads 50 explanations\n2. Flag any explanation that requires EN context to parse",
     "All HI explanations are self-contained",
     "Medium", "Major", "Manual", ""),
]

D_UX_DESIGN = [
    ("Visual hierarchy", "20", "Quiz page primary-action prominence",
     "1. Render quiz page\n2. 5-second test: where does the eye land?\n3. Verify learner notices 'Submit' / 'Check' button first",
     "Submit / Check action is most prominent",
     "Medium", "Major", "Manual", ""),
    ("Visual hierarchy", "20", "Empty-state design (no-progress learner, fresh app)",
     "1. Open app with clear localStorage\n2. Verify empty-state messaging guides next step",
     "Empty-state has clear CTA",
     "Medium", "Major", "Manual", ""),
    ("Visual hierarchy", "20", "Loading-state design for audio + data fetches",
     "1. Throttle network to 3G\n2. Open vocab module\n3. Verify loading indicator appears within 200ms",
     "Loading indicator visible during fetch",
     "Medium", "Minor", "Manual", ""),
    ("Color palette", "21", "Primary color (PRIMARY_DARK = #14452a) contrast against white background",
     "1. Measure WCAG contrast ratio for text using #14452a on #ffffff\n2. Verify ≥ 4.5:1 for body, ≥ 3:1 for large",
     "Contrast ≥ AA standard",
     "Medium", "Major", "Auto", ""),
    ("Color palette", "21", "Link color (#1a5c38) contrast vs primary text",
     "1. Verify links are distinguishable from body text by color alone (and also another cue)",
     "Links pass color-distinguishability check + have underline or other cue",
     "Medium", "Minor", "Manual", ""),
    ("Color palette", "21", "Correct / wrong state colors are color-blind-safe",
     "1. Render correct (green) + wrong (red) feedback states\n2. View through deuteranopia / protanopia simulator",
     "Colorblind users can distinguish; backed by icon/text",
     "Medium", "Major", "Manual", ""),
    ("Typography", "21", "CJK + Devanagari + Latin co-existence on one line",
     "1. Render strings mixing the 3 scripts\n2. Verify font choice doesn't break baseline / line-height",
     "Acceptable typography across 3 scripts",
     "Medium", "Minor", "Manual", ""),
    ("Typography", "21", "Furigana ruby-text size relative to base text",
     "1. Render kanji + furigana\n2. Verify furigana is ~50% size; readable on mobile",
     "Furigana readable on smallest target device",
     "Medium", "Major", "Manual", ""),
    ("Typography", "21", "Japanese punctuation handling (、 。 「 」) line-wrapping rules",
     "1. Render long Japanese sentences with various punctuation\n2. Verify 行頭禁則 (no 。 at line start)",
     "Punctuation follows JIS X 4051 ish convention",
     "Low-Medium", "Minor", "Manual", ""),
    ("Information architecture", "23", "Module taxonomy clarity (Grammar / Vocab / Kanji / Reading / Listening / Mock)",
     "1. New user given app; 30-second task: 'find vocabulary practice'\n2. Time to discovery",
     "≤ 5 seconds to find a module from home",
     "Medium", "Major", "Manual", ""),
    ("Information architecture", "23", "Cross-link integrity between vocab and grammar",
     "1. Open a vocab entry that references a grammar pattern\n2. Click the cross-link\n3. Verify it navigates correctly",
     "All cross-links resolve and navigate",
     "Medium", "Major", "Manual", ""),
    ("Information architecture", "23", "Search / global-find functionality",
     "1. Search for 'taberu' / 'たべる' / '食べる'\n2. Verify all three forms return the same entry",
     "Cross-script search works",
     "Medium", "Major", "Manual", ""),
    ("Onboarding", "24", "Day-1 experience for a brand-new learner",
     "1. Clear app state\n2. New learner asked to use app for 10 min\n3. Observe friction points",
     "Learner completes ≥1 lesson + ≥1 quiz",
     "Medium", "Major", "Manual", ""),
    ("Onboarding", "24", "Self-assessment / placement at start",
     "1. New user: does app ask 'have you studied before?'\n2. Verify pathway adjusts",
     "App accommodates prior-knowledge variance",
     "Low-Medium", "Minor", "Manual", ""),
    ("Cognitive load", "25", "Chunk size per grammar lesson (≤ 5 examples?)",
     "1. Measure example count per pattern\n2. Verify ≤ 7 examples per single-screen view",
     "Per-screen chunk ≤ working-memory budget",
     "Medium", "Minor", "Manual", ""),
    ("Cognitive load", "25", "Per-session card budget enforcement",
     "1. Verify SRS module caps daily new-card intake (e.g., 20 new cards/day)",
     "Daily-cap exists and prevents burnout",
     "Medium", "Minor", "Manual", ""),
    ("Microinteractions", "22", "Correct-answer animation timing",
     "1. Submit correct answer\n2. Measure feedback animation duration\n3. Verify ≤ 1 sec",
     "Fast feedback (≤ 1s) to maintain flow",
     "Low-Medium", "Minor", "Manual", ""),
    ("Microinteractions", "22", "Wrong-answer feedback informativeness",
     "1. Submit wrong answer\n2. Verify learner sees: correct answer, why wrong, link to lesson",
     "Wrong-answer feedback teaches, not just punishes",
     "Medium", "Major", "Manual", ""),
    ("Form / input", "27", "Japanese IME input for production drills",
     "1. Open production-type drill (EN→JA typing)\n2. Type with IME on Mac / Windows / iOS / Android\n3. Verify submission",
     "IME input works across platforms",
     "Medium", "Major", "Manual", ""),
    ("Form / input", "27", "Romaji-to-kana auto-conversion for learners without IME",
     "1. Toggle romaji-input mode\n2. Type 'tabemasu'\n3. Verify auto-conversion to たべます",
     "Romaji mode works for IME-less learners",
     "Medium", "Major", "Manual", ""),
    ("Form / input", "27", "Partial-credit grading on near-miss typing",
     "1. Submit たべます when correct is 食べます\n2. Verify grading accepts kana form for kanji-target (or flags partial)",
     "Partial-credit policy is consistent",
     "Medium", "Major", "Manual", "Procedure manual references 50% partial-credit (Bunpro-style)"),
    ("Dark mode", "28", "Dark-mode availability + WCAG contrast in dark",
     "1. Toggle dark mode (if available)\n2. Verify all text contrasts ≥ 4.5:1 against dark background",
     "Dark mode meets WCAG-AA",
     "Low", "Minor", "Manual", "Not currently implemented"),
    ("Gamification", "26", "Streak / progress visualization motivates returns",
     "1. Use app daily for 5 days\n2. Verify streak counter visible\n3. Verify break-in-streak isn't punishing",
     "Streak motivates without punishing",
     "Low", "Minor", "Manual", ""),
]

E_ACCESSIBILITY = [
    ("WCAG-AA", "29", "Color-contrast ratio across all text-on-background combinations",
     "1. Run automated contrast checker (axe-core / Lighthouse)\n2. Verify ≥ 4.5:1 for body, ≥ 3:1 for large",
     "All combinations pass AA",
     "Medium", "Major", "Auto", ""),
    ("WCAG-AA", "29", "Semantic HTML: proper heading hierarchy + landmarks",
     "1. Run axe-core\n2. Verify H1→H2→H3 hierarchy (no skips)\n3. Verify <main>, <nav>, <header>, <footer> landmarks",
     "Heading + landmark structure passes axe",
     "Medium", "Major", "Auto", ""),
    ("WCAG-AA", "29", "ARIA labels on all interactive controls",
     "1. Inspect all buttons / links / inputs\n2. Verify aria-label or visible label",
     "0 unlabeled interactive controls",
     "Medium", "Major", "Auto", ""),
    ("WCAG-AA", "29", "Keyboard-only navigation through entire app",
     "1. Disconnect mouse\n2. Tab through all routes\n3. Verify all controls reachable + actionable",
     "Full keyboard navigation possible",
     "Medium", "Major", "Manual", ""),
    ("WCAG-AA", "29", "Focus-indicator visibility",
     "1. Tab through controls\n2. Verify focus ring is visible (≥3:1 contrast against background)",
     "Focus indicator always visible",
     "Medium", "Major", "Manual", ""),
    ("WCAG-AA", "29", "Skip-to-main link at page top",
     "1. Tab once after page load\n2. Verify 'Skip to main content' link appears",
     "Skip-link present and functional",
     "Medium", "Minor", "Manual", ""),
    ("Screen reader", "30", "VoiceOver (macOS) reads Japanese text with correct language tag",
     "1. Enable VoiceOver\n2. Navigate Japanese passages\n3. Verify reader uses Japanese voice (not English mis-pronouncing kanji)",
     "Japanese text reads in Japanese voice",
     "Medium", "Major", "Manual", "Needs <span lang='ja'> tags"),
    ("Screen reader", "30", "NVDA (Windows) reads mixed Japanese + Hindi + English correctly",
     "1. Enable NVDA\n2. Navigate quiz with all three locales visible\n3. Verify per-language voice switching",
     "Per-language voices used",
     "Medium", "Major", "Manual", ""),
    ("Screen reader", "30", "TalkBack (Android) navigation through learn-vocab page",
     "1. Enable TalkBack\n2. Swipe through vocab card\n3. Verify each element announces clearly",
     "All elements announced",
     "Medium", "Major", "Manual", ""),
    ("Screen reader", "30", "Furigana exposure to screen reader (ruby tag handling)",
     "1. Enable VoiceOver\n2. Read kanji with furigana\n3. Verify reader uses ruby reading (not skip)",
     "Furigana read or kanji read; not silenced",
     "Medium", "Major", "Manual", ""),
    ("Motor", "31", "Touch-target size ≥ 48x48 px on mobile",
     "1. Render quiz on 360px wide viewport\n2. Measure all tap targets",
     "All targets ≥ 48x48",
     "Low-Medium", "Minor", "Auto", ""),
    ("Motor", "31", "Keyboard-shortcut customization for power users",
     "1. Verify common actions (next question, mark correct, replay audio) have shortcuts\n2. Verify shortcuts don't conflict with screen-reader",
     "Shortcuts exist + don't conflict",
     "Low", "Minor", "Manual", ""),
    ("Cognitive accessibility", "32", "Reduced-motion preference respect",
     "1. Set OS prefers-reduced-motion = true\n2. Verify app disables transitions / animations",
     "Reduced-motion respected",
     "Low-Medium", "Minor", "Manual", ""),
    ("Cognitive accessibility", "32", "Dyslexia-friendly font option",
     "1. Verify font is dyslexia-friendly (OpenDyslexic toggle?) OR default font is reasonably dyslexia-friendly",
     "Decision documented; option exists if needed",
     "Low", "Minor", "Manual", ""),
    ("Cognitive accessibility", "32", "Reading-flow predictability (no surprise pop-ups)",
     "1. Use app for 20 min\n2. Note unexpected modals / context changes",
     "0 surprise context-shifts",
     "Low-Medium", "Minor", "Manual", ""),
    ("Hearing-impaired", "33", "Audio-dependent items have transcripts visible",
     "1. Open listening.json items\n2. Verify script_ja is visible OR can be revealed",
     "Transcripts accessible",
     "Medium", "Major", "Manual", "JA-86 ensures script_ja exists"),
    ("Hearing-impaired", "33", "Pitch-accent visual representation",
     "1. Verify pitch-accent diagram (drop arrow / line graph) is visible",
     "Visual pitch-accent renders correctly",
     "Medium", "Major", "Manual", ""),
    ("Hearing-impaired", "33", "Mock-exam listening section has 'reveal-script' button",
     "1. In mock-exam mode, listen to a question\n2. Verify learner can reveal script post-answer",
     "Script reveal available post-answer",
     "Medium", "Major", "Manual", ""),
]

F_SECURITY = [
    ("XSS", "34", "Input field XSS payload injection (feedback module if exists)",
     "1. Identify all input surfaces\n2. Submit <script>alert(1)</script>, <img src=x onerror=alert(1)>\n3. Verify no script execution",
     "All inputs sanitized; no payload executes",
     "High", "Critical", "Manual", ""),
    ("XSS", "34", "URL-parameter XSS in route handlers",
     "1. Identify all URL params parsed by JS\n2. Inject XSS payload\n3. Verify no execution",
     "URL params sanitized",
     "High", "Critical", "Manual", ""),
    ("XSS", "34", "localStorage payload injection",
     "1. Manually write XSS payload to known localStorage key\n2. Reload page\n3. Verify app sanitizes on read",
     "localStorage values sanitized on read",
     "High", "Critical", "Manual", ""),
    ("XSS", "34", "JSON-fixture injection (if any user-uploaded JSON path exists)",
     "1. Verify no user-upload paths\n2. If any, test JSON-payload injection",
     "No user-upload OR uploads sanitized",
     "Medium", "Major", "Manual", ""),
    ("CSP", "35", "Content-Security-Policy header strictness",
     "1. Inspect response headers from production deploy\n2. Verify CSP includes default-src 'self'; script-src 'self' 'sha256-...'\n3. No unsafe-inline / unsafe-eval",
     "Strict CSP without unsafe-*",
     "Medium", "Major", "Auto", ""),
    ("CSP", "35", "frame-ancestors / X-Frame-Options (clickjacking)",
     "1. Verify CSP frame-ancestors 'none' OR X-Frame-Options DENY",
     "Embedding prevented",
     "Medium", "Major", "Auto", ""),
    ("CSP", "35", "Referrer-Policy header",
     "1. Verify Referrer-Policy = strict-origin-when-cross-origin or stricter",
     "Referrer leak prevented",
     "Low-Medium", "Minor", "Auto", ""),
    ("CSP", "35", "Permissions-Policy header (mic / camera / geolocation)",
     "1. Verify Permissions-Policy disables unused features",
     "Unused features denied",
     "Low-Medium", "Minor", "Auto", ""),
    ("Supply chain", "36", "npm dependency CVE scan",
     "1. Run npm audit\n2. Verify 0 high/critical CVEs",
     "0 high/critical CVEs",
     "Medium", "Major", "Auto", ""),
    ("Supply chain", "36", "Python dependency CVE scan (pip-audit / safety)",
     "1. Run pip-audit on tools/requirements.txt\n2. Verify 0 high/critical",
     "0 high/critical CVEs",
     "Medium", "Major", "Auto", ""),
    ("Supply chain", "36", "Transitive-dependency license-compliance scan",
     "1. Run license-checker / pip-licenses\n2. Verify no GPL contamination (project license is MIT or similar)",
     "License-clean",
     "Medium", "Major", "Auto", ""),
    ("Supply chain", "36", "GitHub Actions third-party-action pinning by SHA",
     "1. Inspect .github/workflows/*.yml\n2. Verify external actions pinned by SHA, not tag",
     "All third-party actions SHA-pinned",
     "Medium", "Major", "Manual", ""),
    ("Supply chain", "36", "Subresource Integrity (SRI) for any CDN assets",
     "1. Inspect any <script src='cdn...'> or <link href='cdn...'>\n2. Verify integrity= attribute present",
     "SRI present where applicable",
     "Low-Medium", "Minor", "Manual", ""),
    ("Secrets", "37", "Git-history scan for accidentally-committed tokens",
     "1. Run trufflehog / git-secrets across full history\n2. Verify 0 high-confidence hits",
     "0 leaked secrets in history",
     "Medium", "Critical", "Auto", "Never formally scanned"),
    ("Secrets", "37", ".env files / private keys in tree",
     "1. ls-files for .env / .pem / .key / credentials.json\n2. Verify absence + .gitignore covers these",
     "0 secret files present",
     "Medium", "Critical", "Auto", ""),
    ("Penetration", "38", "Static-site dynamic-surface enumeration",
     "1. Crawl the site\n2. Identify any JS-driven dynamic-data writes (localStorage, feedback POSTs)",
     "Dynamic-surface enumeration documented",
     "Low", "Major", "Manual", ""),
    ("Penetration", "38", "Rate-limit / DoS surface on any POST endpoints",
     "1. Identify any POST endpoints\n2. Verify rate-limit or static-only architecture",
     "Static-only OR rate-limited",
     "Low", "Major", "Manual", ""),
    ("GitHub Actions", "39", "Workflow permissions: least-privilege token scopes",
     "1. Inspect permissions: blocks in workflows\n2. Verify least-priv (e.g., contents:read, not write unless needed)",
     "All workflows least-priv",
     "Medium", "Major", "Manual", ""),
    ("GitHub Actions", "39", "Pull-request workflow protection (no secret access on fork PRs)",
     "1. Verify workflows use pull_request not pull_request_target where appropriate",
     "Fork PRs can't access secrets",
     "Medium", "Critical", "Manual", ""),
]

G_PRIVACY_LEGAL = [
    ("Privacy", "40", "Telemetry / analytics actually-zero verification",
     "1. Open app, monitor network tab\n2. Verify no analytics POSTs (Google Analytics, Mixpanel, etc.)",
     "0 outbound analytics traffic",
     "Medium", "Major", "Manual", "Project claims no tracking; verify"),
    ("Privacy", "40", "localStorage content audit (no PII)",
     "1. Inspect localStorage after typical use\n2. Verify only progress + preferences; no PII",
     "0 PII in localStorage",
     "Medium", "Major", "Manual", ""),
    ("Privacy", "40", "Cookie use audit",
     "1. Inspect cookies after app use\n2. Verify essential-only (or zero)",
     "Essential cookies only",
     "Medium", "Minor", "Manual", ""),
    ("Privacy", "40", "GDPR Article 13 disclosures (if EU users)",
     "1. Verify privacy policy exists\n2. Check it covers GDPR points if applicable",
     "Privacy policy present",
     "Medium", "Major", "Manual", ""),
    ("Privacy", "40", "DPDP Act (India) compliance",
     "1. Verify Hindi/English privacy disclosure for Indian users\n2. Check data-fiduciary registration if required",
     "DPDP applicable + compliant",
     "Medium", "Major", "Manual", "India-specific"),
    ("Cookies / consent", "41", "Cookie-consent banner if any third-party scripts load",
     "1. If Google Fonts / CDN / analytics loads, verify consent flow\n2. If zero third-party, document",
     "Consent OR zero-third-party documented",
     "Low", "Minor", "Manual", ""),
    ("COPPA", "42", "Minor-user (<13) data-collection check",
     "1. If app has account system, verify age gate\n2. If no accounts, document COPPA-out-of-scope",
     "Compliant per audience age",
     "Low-Medium", "Minor", "Manual", ""),
    ("License compliance", "43", "kanjium CC-BY-SA 4.0 attribution surface visibility",
     "1. Open app\n2. Find pitch-accent data attribution\n3. Verify visible per CC-BY-SA terms",
     "Attribution clearly visible",
     "Medium", "Major", "Manual", "Currently in data/_meta; UI exposure?"),
    ("License compliance", "43", "Audio-source licensing (VOICEVOX, speaker voice)",
     "1. Verify VOICEVOX usage complies with its license\n2. Verify Tsumugi (speaker 8) voice usage rights",
     "VOICEVOX + voice licensing compliant",
     "Medium", "Major", "Manual", ""),
    ("License compliance", "43", "Open-source LICENSE file accurate to repo content",
     "1. Verify LICENSE file matches actual license intent\n2. Verify content-license is distinguished from code-license",
     "LICENSE accurate; CONTENT-LICENSE.md handles content",
     "Medium", "Major", "Manual", "CONTENT-LICENSE.md mentioned in N5Improvement.txt"),
    ("License compliance", "43", "Transitive npm-license compatibility",
     "1. license-checker scan\n2. Verify no GPL / AGPL contamination if project is MIT/Apache",
     "License-clean",
     "Medium", "Major", "Auto", ""),
    ("Brand / trademark", "44", "'JLPT' trademark usage compliance",
     "1. Verify any 'JLPT' references include 'JLPT is a registered trademark of...' disclaimer\n2. Verify app doesn't imply JEES affiliation",
     "Trademark disclaimer present + no affiliation implied",
     "Low-Medium", "Minor", "Manual", ""),
    ("Brand / trademark", "44", "App-name trademark search (JLPT N5 Tutor / JLPTSuccess)",
     "1. Trademark search in India + Japan + US\n2. Verify no conflict",
     "No trademark conflict",
     "Low", "Minor", "Manual", ""),
    ("Advertising / claims", "45", "Claim accuracy: 'free, complete, local-audio, no-tracking'",
     "1. Verify each claim against actual app state\n2. Flag any false claim",
     "All claims accurate",
     "Medium", "Major", "Manual", "From N5Improvement.txt strategic framing"),
    ("Advertising / claims", "45", "'Pass the JLPT N5' or similar outcome claim",
     "1. Search marketing copy for outcome claims\n2. Verify backed by data OR softened",
     "Outcome claims backed or removed",
     "Low", "Minor", "Manual", ""),
]

H_PERFORMANCE = [
    ("Core Web Vitals", "46", "LCP (Largest Contentful Paint) < 2.5s on 3G",
     "1. Throttle to slow 3G\n2. Load homepage\n3. Measure LCP",
     "LCP < 2.5s",
     "Medium", "Major", "Auto", "Lighthouse"),
    ("Core Web Vitals", "46", "FID / INP < 100ms",
     "1. Load app, interact within 1s of load\n2. Measure FID/INP",
     "FID/INP < 100ms",
     "Medium", "Major", "Auto", ""),
    ("Core Web Vitals", "46", "CLS < 0.1",
     "1. Load app\n2. Observe layout shifts during load\n3. Measure CLS",
     "CLS < 0.1",
     "Medium", "Major", "Auto", ""),
    ("Bundle size", "46", "Total JS bundle size on initial load",
     "1. Measure first-load JS\n2. Verify < 300KB compressed",
     "JS budget met",
     "Medium", "Major", "Auto", ""),
    ("Bundle size", "46", "Per-route code-splitting effectiveness",
     "1. Verify each module loads its own chunk\n2. Verify shared bundle doesn't bloat",
     "Code-splitting works",
     "Low-Medium", "Minor", "Auto", ""),
    ("Audio cache", "47", "Service-worker audio precache strategy",
     "1. Inspect sw.js precache list\n2. Verify per-module audio precached on first visit",
     "Per-module audio cached",
     "Medium", "Major", "Manual", ""),
    ("Audio cache", "47", "Storage-quota management for 1782 grammar MP3s + others",
     "1. Estimate total audio size (~100MB+)\n2. Verify cache eviction policy",
     "Quota managed; eviction policy documented",
     "Medium", "Major", "Manual", ""),
    ("Audio cache", "47", "Offline-mode availability per module",
     "1. Load module while online\n2. Disconnect\n3. Verify module fully functional offline",
     "Modules work offline post-first-visit",
     "Medium", "Major", "Manual", ""),
    ("PWA", "48", "Installability on iOS Safari / Android Chrome / desktop Chrome",
     "1. Open app on each\n2. Verify 'Add to Home Screen' / install prompt",
     "Installable everywhere",
     "Medium", "Major", "Manual", ""),
    ("PWA", "48", "Service-worker update strategy (cache-busting on deploy)",
     "1. Deploy new version with CACHE_VERSION bump\n2. Verify existing users get new version within 1 reload",
     "Update propagates in ≤ 1 reload",
     "Medium", "Major", "Manual", "Procedure manual references CACHE_VERSION discipline"),
    ("PWA", "48", "Offline-error UX (no-connection scenario)",
     "1. Disconnect\n2. Open uncached route\n3. Verify graceful error + retry",
     "Offline error is informative",
     "Medium", "Major", "Manual", ""),
    ("Cross-browser", "49", "Safari iOS audio autoplay restriction handling",
     "1. Open audio drill on iOS Safari\n2. Verify play requires user gesture\n3. Verify subsequent plays don't",
     "Audio works post-first-tap",
     "Medium", "Major", "Manual", ""),
    ("Cross-browser", "49", "Firefox MP3 decoder behavior",
     "1. Play all 1782 MP3s on Firefox\n2. Verify no decode failures",
     "All MP3s decode in Firefox",
     "Low-Medium", "Minor", "Manual", ""),
    ("Cross-browser", "49", "Older-Android Chrome (≤ Chrome 90) rendering",
     "1. Test on Android 8/9 with Chrome 90\n2. Verify app loads + functions",
     "Functional on older Chrome",
     "Low-Medium", "Minor", "Manual", ""),
    ("Mobile-responsive", "50", "Sub-360px viewport rendering",
     "1. Set viewport to 320px wide\n2. Verify no horizontal scroll, no overflow",
     "No horizontal scroll at 320px",
     "Medium", "Major", "Auto", ""),
    ("Mobile-responsive", "50", "Portrait vs landscape orientation",
     "1. Rotate device during quiz\n2. Verify state preserved + layout adapts",
     "Orientation change non-destructive",
     "Medium", "Major", "Manual", ""),
    ("Mobile-responsive", "50", "Notched-device safe-area handling (iPhone X+)",
     "1. Render on iPhone X simulator\n2. Verify no content under notch / home indicator",
     "Safe-area respected",
     "Low-Medium", "Minor", "Manual", ""),
    ("Font rendering", "51", "Noto Sans CJK availability fallback",
     "1. Simulate user without Noto fonts\n2. Verify graceful fallback",
     "Fallback acceptable",
     "Low-Medium", "Minor", "Manual", ""),
    ("Font rendering", "51", "Mixed-script line-height consistency",
     "1. Render lines with JA + HI + EN\n2. Measure line-height variance",
     "Line-height consistent",
     "Low-Medium", "Minor", "Manual", ""),
    ("i18n", "52", "Locale-switch state retention",
     "1. Mid-session HI ↔ EN toggle\n2. Verify learner progress preserved",
     "State persists across toggle",
     "Medium", "Major", "Manual", ""),
    ("i18n", "52", "Text-expansion handling for Hindi (often 30% longer)",
     "1. Render UI in HI\n2. Verify no truncation / overflow in buttons / labels",
     "0 truncated HI labels",
     "Medium", "Major", "Manual", ""),
    ("SEO", "53", "Sitemap.xml presence + accuracy",
     "1. Verify /sitemap.xml exists\n2. Verify it includes all routes",
     "Sitemap accurate",
     "Low-Medium", "Minor", "Auto", ""),
    ("SEO", "53", "Per-page meta-description + Open Graph tags",
     "1. Inspect each route's <head>\n2. Verify unique meta-description + og:title / og:image",
     "Meta complete per route",
     "Low", "Minor", "Auto", ""),
    ("SEO", "53", "Canonical-URL handling",
     "1. Verify <link rel='canonical'> on each route\n2. Verify trailing-slash handling",
     "Canonical URLs correct",
     "Low", "Minor", "Auto", ""),
]

I_DATA_ENG = [
    ("Schema validation", "54", "JSON-schema validation for all data/*.json beyond CI invariants",
     "1. Write formal JSON-schema for each file\n2. Run validator on every release",
     "All files validate",
     "Medium", "Major", "Auto", "93 invariants cover most fields; schema is sharper"),
    ("Schema validation", "54", "Field-presence invariants for new fields",
     "1. When new field added, ensure presence-check invariant in tools/check_content_integrity.py",
     "New fields locked",
     "Medium", "Major", "Manual", "Discipline check"),
    ("Schema validation", "54", "Cross-corpus FK integrity (vocab_id, grammarPatternId, kbSourceId)",
     "1. Wave-1 covers vocab_id + grammarPatternId\n2. Add kbSourceId check",
     "All FKs resolve",
     "Medium", "Major", "Auto", "AUDIT-COVERAGE lists kbSourceId as not-yet-CI-enforced"),
    ("Schema versioning", "55", "Schema-version field per data file",
     "1. Add `_meta.schema_version` to each data/*.json\n2. Bump on migration",
     "All files versioned",
     "Medium", "Major", "Manual", ""),
    ("Schema versioning", "55", "Migration script presence for past version bumps",
     "1. Audit any past migration\n2. Verify reversible migration script exists",
     "Migrations documented + reversible",
     "Medium", "Minor", "Manual", ""),
    ("CACHE_VERSION", "55", "CACHE_VERSION bump discipline",
     "1. On any data/*.json change, verify CACHE_VERSION bumped\n2. Verify version.json updated",
     "Cache-bust on data changes",
     "Medium", "Major", "Manual", "Procedure manual codifies this"),
    ("Backup", "56", "data/*.json.bak_* policy adherence",
     "1. Verify backup files never overwritten (versioned _v2, _v3)\n2. Verify backup naming convention enforced",
     "Backup discipline followed",
     "Medium", "Major", "Manual", "Project-CLAUDE.md backup policy"),
    ("Backup", "56", "Repo-level disaster recovery (release-bundle workaround)",
     "1. Verify backup-bundle release exists\n2. Verify it can restore the repo",
     "DR procedure works",
     "Low-Medium", "Major", "Manual", ""),
    ("Build / CI", "57", "tools/check_content_integrity.py runs in CI on every PR",
     "1. Inspect .github/workflows/\n2. Verify CI runs the script",
     "CI runs integrity check",
     "Medium", "Critical", "Auto", ""),
    ("Build / CI", "57", "Determinism: same input → same output across machines",
     "1. Run build on two machines\n2. Verify byte-identical output",
     "Deterministic build",
     "Low-Medium", "Minor", "Manual", ""),
    ("Build / CI", "57", "CI runtime budget (build + tests < 5 min)",
     "1. Measure CI duration\n2. Verify under budget",
     "CI fast",
     "Low", "Minor", "Auto", ""),
    ("Versioning", "55", "Audit-coverage doc dated correctly + reflecting current commit",
     "1. Open AUDIT-COVERAGE-YYYY-MM-DD.md\n2. Verify date matches last data-change commit",
     "Coverage doc current",
     "Medium", "Minor", "Manual", "Per Rule 4"),
]

J_PEDAGOGY = [
    ("SLA", "58", "Comprehensible-input level (i+1) calibration per lesson",
     "1. For each grammar pattern, verify example sentences use ≥80% known vocab (assuming prior patterns + their vocab)",
     "≥80% known-vocab per example given dependency graph",
     "Medium", "Major", "Auto+Manual", ""),
    ("SLA", "58", "Output-hypothesis adherence: production drills exist per pattern",
     "1. Verify each grammar pattern has ≥1 production-type drill in drills_auto.json",
     "Production drills cover all patterns",
     "Medium", "Major", "Auto", ""),
    ("SLA", "58", "Comprehensible-output: receptive vs productive balance",
     "1. Count receptive (mcq) vs productive (production) drills\n2. Verify reasonable balance (e.g., 70/30)",
     "Balance documented + justified",
     "Low-Medium", "Minor", "Auto", ""),
    ("SRS", "59", "SM-2 / FSRS implementation correctness",
     "1. Read SRS implementation in JS\n2. Verify ease-factor + interval calculations match spec",
     "Algorithm correct per spec",
     "Medium", "Major", "Manual", ""),
    ("SRS", "59", "Review-interval calibration: do failed cards reappear soon?",
     "1. Fail a card\n2. Verify next-review-time decreased appropriately",
     "Failed cards return sooner",
     "Medium", "Major", "Manual", ""),
    ("SRS", "59", "Burnout prevention: daily-new-card cap",
     "1. Verify cap exists (e.g., 20 new/day)\n2. Verify learner can override consciously",
     "Cap + override exists",
     "Medium", "Minor", "Manual", ""),
    ("Curriculum", "60", "Grammar-pattern dependency graph correctness",
     "1. Verify each pattern's prerequisites list\n2. Verify graph is acyclic",
     "Dependency graph valid",
     "Medium", "Major", "Auto+Manual", ""),
    ("Curriculum", "60", "Vocab-introduction order: easier-first",
     "1. Verify high-frequency vocab introduced before low-frequency\n2. Verify tier-flags drive order",
     "Order respects frequency tiers",
     "Medium", "Major", "Manual", ""),
    ("Curriculum", "60", "Kanji-radical-decomposition order",
     "1. Verify radicals introduced before kanji that contain them\n2. Verify simple kanji before complex compounds",
     "Order respects radical-first principle",
     "Medium", "Major", "Manual", ""),
    ("Assessment", "61", "Mock-exam item face-validity (looks like real JLPT?)",
     "1. JLPT-experienced reviewer judges mock items\n2. Rate each as 'looks JLPT' / 'doesn't'",
     "≥90% pass face-validity",
     "Low-Medium", "Major", "Manual", ""),
    ("Assessment", "61", "Mock-exam construct-validity (tests what JLPT tests)",
     "1. Map each mock-item to a JLPT skill (reading-comprehension / grammar-knowledge / etc.)\n2. Verify coverage",
     "All JLPT-N5 skills covered",
     "Low-Medium", "Major", "Manual", ""),
    ("Comparative", "62", "Genki I+II alignment of grammar patterns",
     "1. Map each shipped pattern to Genki chapter\n2. Verify reasonable coverage",
     "Alignment documented",
     "Medium", "Minor", "Manual", ""),
    ("Comparative", "62", "Minna no Nihongo alignment",
     "1. Similar mapping to Minna lessons 1-25",
     "Alignment documented",
     "Medium", "Minor", "Manual", ""),
    ("Hindi-L1 error anticipation", "63", "Postposition-mapping confusions (Hindi का / से / को → Japanese particles)",
     "1. List known Hindi-speaker errors in Japanese (e.g., overuse of で for से)\n2. Verify explanations address them",
     "Common HI-L1 errors addressed",
     "Low-Medium", "Minor", "Manual", ""),
    ("Hindi-L1 error anticipation", "63", "Word-order transfer errors (SOV → SOV, but particle confusion)",
     "1. Identify Hindi-speakers' typical Japanese word-order errors\n2. Verify explanations address them",
     "Word-order errors addressed",
     "Low-Medium", "Minor", "Manual", ""),
]

K_QA = [
    ("Exploratory", "64", "30-min adversarial use session",
     "1. Tester uses app for 30 min trying to break it\n2. Log all bugs / friction",
     "≤ 3 critical / major bugs per session",
     "Medium", "Major", "Manual", ""),
    ("Exploratory", "64", "Concurrent-tab behavior",
     "1. Open app in 3 tabs simultaneously\n2. Use each\n3. Verify state isolation OR consistent sync",
     "Multi-tab behavior documented",
     "Low-Medium", "Minor", "Manual", ""),
    ("Exploratory", "64", "Slow-network behavior",
     "1. Throttle to slow 3G\n2. Verify all flows still complete (with loading states)",
     "Slow-network usable",
     "Medium", "Major", "Manual", ""),
    ("Exploratory", "64", "Browser back/forward button behavior",
     "1. Use app, hit back/forward many times\n2. Verify state preserved correctly",
     "History navigation correct",
     "Medium", "Major", "Manual", ""),
    ("Automation", "65", "Unit-test coverage for tools/*.py",
     "1. Run pytest with coverage\n2. Verify ≥80% line coverage",
     "≥80% coverage",
     "Medium", "Major", "Auto", ""),
    ("Automation", "65", "Integration tests for data-loading + rendering",
     "1. Verify tests load data/*.json + assert render output",
     "Integration tests pass",
     "Medium", "Major", "Auto", ""),
    ("Automation", "65", "E2E test of complete user flow (vocab study → quiz → results)",
     "1. Playwright/Cypress script for full flow\n2. Run in CI",
     "E2E suite green",
     "Medium", "Major", "Auto", ""),
    ("Automation", "65", "Smoke test on every deploy",
     "1. Post-deploy hook hits homepage + each module route\n2. Verify HTTP 200 + key text",
     "Smoke green on every deploy",
     "Medium", "Critical", "Auto", ""),
    ("Visual regression", "66", "Pixel-diff baseline for each route",
     "1. Capture golden screenshots\n2. On each deploy, diff against baseline",
     "0 unexpected pixel diffs",
     "Low-Medium", "Minor", "Auto", ""),
    ("Visual regression", "66", "Layout-shift detection",
     "1. Record CLS during load\n2. Flag regressions vs baseline",
     "CLS doesn't regress",
     "Low-Medium", "Minor", "Auto", ""),
    ("Localization", "67", "Locale-toggle test on every route",
     "1. For each route, toggle EN ↔ HI\n2. Verify all visible text changes",
     "0 untranslated strings on HI",
     "Medium", "Major", "Manual", ""),
    ("Localization", "67", "Text-expansion on Hindi (UI overflow)",
     "1. Render every page in HI\n2. Verify no truncation",
     "0 truncated HI labels",
     "Medium", "Major", "Manual", ""),
    ("Audio playback", "68", "Per-browser autoplay policy compliance",
     "1. Test audio playback on Chrome / Safari / Firefox / Edge\n2. Verify user-gesture requirement satisfied",
     "Audio plays after gesture, doesn't autoplay",
     "Medium", "Major", "Manual", ""),
    ("Audio playback", "68", "MP3 vs WebM codec fallback",
     "1. Verify MP3 plays everywhere\n2. If WebM is fallback, verify on supporting browsers",
     "Codec works cross-browser",
     "Low-Medium", "Minor", "Manual", ""),
    ("Audio playback", "68", "Preload strategy: do audio files preload on hover / proximity?",
     "1. Inspect <audio preload=...> attrs\n2. Verify reasonable preload behavior",
     "Preload tuned for UX",
     "Low-Medium", "Minor", "Manual", ""),
]

L_CULTURAL_ETHICAL = [
    ("Cultural sensitivity (JA)", "69", "Stereotype-avoidance in dialogue / authentic items",
     "1. Native Japanese reviewer reads all listening.json + authentic.json\n2. Flag stereotyped characters",
     "0 stereotyped depictions",
     "Medium", "Major", "Manual", ""),
    ("Cultural sensitivity (JA)", "69", "Appropriate cultural-context items (festivals, social norms)",
     "1. Verify cultural items represent contemporary Japan accurately\n2. Flag outdated or stereotyped portrayals",
     "Cultural content accurate + respectful",
     "Medium", "Major", "Manual", ""),
    ("Cultural sensitivity (JA)", "69", "Gender-balance in dialogue speaker roles",
     "1. Count male vs female speakers across listening.json\n2. Verify roles aren't gender-stereotyped",
     "Balanced gender representation",
     "Medium", "Minor", "Manual", ""),
    ("Cultural sensitivity (HI)", "70", "Indian-cultural-context items (if any) accuracy",
     "1. Verify any Hindi-locale cultural references are accurate\n2. Verify Indian names used appropriately",
     "Indian-context accurate",
     "Medium", "Major", "Manual", ""),
    ("Cultural sensitivity (HI)", "70", "Pan-Indian neutrality (avoid Bombay/Delhi-specific)",
     "1. Native Hindi reviewer flags regionally-marked content\n2. Replace with neutral equivalents",
     "0 regionally-marked items",
     "Low-Medium", "Minor", "Manual", ""),
    ("Cultural sensitivity (HI)", "70", "Religious-festival neutrality",
     "1. Verify any festival references are presented neutrally (or rotate across festivals)",
     "Festival representation neutral",
     "Low", "Minor", "Manual", ""),
    ("AI ethics / disclosure", "71", "UI-level LLM-curation disclosure",
     "1. Verify app has visible 'Content authored by AI, not native-reviewed' disclosure\n2. Verify it's not buried",
     "Disclosure visible to learners",
     "Medium", "Major", "Manual", "Currently only in CONTENT-LICENSE.md + AUDIT-COVERAGE"),
    ("AI ethics / disclosure", "71", "Provenance per-entry transparency",
     "1. Per N5Improvement IMP-184 Avoid: provenance is NOT shown as UI trust signal\n2. Verify",
     "Provenance not shown as trust signal",
     "Medium", "Major", "Manual", "Already decided Avoid"),
    ("AI ethics / disclosure", "71", "Confidence levels exposed appropriately (pitch-accent unverified)",
     "1. For `confidence: unverified` entries, verify learner-facing indication of lower confidence",
     "Unverified items flagged in UI OR documented choice not to",
     "Medium", "Minor", "Manual", ""),
    ("Trust & safety", "72", "Feedback module content moderation (if UGC)",
     "1. If app accepts user feedback text, verify moderation flow\n2. If no UGC, document",
     "UGC moderated OR not present",
     "Low", "Minor", "Manual", ""),
]

M_OPERATIONS = [
    ("DevOps", "73", "Deploy rollback procedure",
     "1. Push a bad deploy intentionally\n2. Verify rollback < 5 min",
     "Rollback works",
     "Low", "Major", "Manual", ""),
    ("DevOps", "73", "Uptime monitoring (e.g., UptimeRobot)",
     "1. Verify external monitor pings homepage\n2. Verify alert on downtime",
     "Monitoring + alerting active",
     "Low", "Minor", "Manual", ""),
    ("DevOps", "73", "CI-failure alerting",
     "1. Cause CI failure\n2. Verify maintainer notified",
     "CI alerts work",
     "Low-Medium", "Minor", "Manual", ""),
    ("Analytics", "74", "Privacy-respecting analytics verification (or zero-analytics)",
     "1. Inspect production network for analytics calls\n2. Verify either zero OR privacy-respecting (Plausible / Fathom)",
     "Privacy-respecting OR zero",
     "Low", "Minor", "Manual", "Currently claims zero tracking"),
    ("Customer support", "75", "Feedback-triage SLA",
     "1. Submit a test feedback item\n2. Measure time to acknowledgment",
     "SLA met (e.g., 48h)",
     "Low", "Minor", "Manual", "N5/feedback/ files exist"),
    ("Customer support", "75", "Feedback-to-fix conversion rate",
     "1. Audit last 10 feedback items\n2. Verify each has a disposition (fixed / deferred / wontfix)",
     "All feedback items dispositioned",
     "Low", "Minor", "Manual", ""),
    ("Documentation", "76", "README accuracy (matches actual state)",
     "1. Read README\n2. Verify every claim matches repo",
     "README accurate",
     "Low-Medium", "Minor", "Manual", ""),
    ("Documentation", "76", "Contribution guide accuracy",
     "1. New contributor follows CONTRIBUTING.md\n2. Verify steps work",
     "Onboarding-by-doc works",
     "Low", "Minor", "Manual", ""),
    ("Documentation", "76", "Cross-link integrity within /docs",
     "1. Render all docs/*.md\n2. Verify all internal links resolve",
     "0 broken doc links",
     "Low", "Minor", "Auto", ""),
    ("Documentation", "76", "Audit-coverage doc dated correctly + reflecting current commit",
     "1. Open AUDIT-COVERAGE-YYYY-MM-DD.md\n2. Verify date matches last data-change commit",
     "Coverage doc current",
     "Low-Medium", "Minor", "Manual", "Per Rule 4 propagation"),
]

N_END_USER_POV = [
    ("Primary persona", "77", "Hindi-L1 + EN-L2 + JA-L3 learner first session",
     "1. Recruit such learner\n2. Observe 30-min session\n3. Note language-switching cognitive load",
     "Learner completes ≥1 module without aborting",
     "Medium", "Major", "Manual", ""),
    ("Primary persona", "77", "Mid-session locale toggle behavior",
     "1. Learner toggles EN ↔ HI mid-lesson\n2. Verify state preserved + content adapts",
     "Toggle is non-destructive",
     "Medium", "Major", "Manual", ""),
    ("Self-study", "78", "Day-1 learner can complete a full vocab session unaided",
     "1. New learner, no instructor\n2. Verify they finish 1 vocab session",
     "≥80% completion without help",
     "Medium", "Major", "Manual", ""),
    ("Self-study", "79", "Pacing expectations set clearly (e.g., 30 min/day for 6 months)",
     "1. Verify app communicates expected pace\n2. Verify learner can adjust",
     "Pace communicated",
     "Low-Medium", "Minor", "Manual", ""),
    ("Classroom instructor", "79", "Instructor uses app as Genki-adjunct",
     "1. Instructor maps Genki chapter to N5 patterns\n2. Assigns app modules as homework",
     "Mapping is easy + works",
     "Low-Medium", "Minor", "Manual", ""),
    ("Classroom instructor", "79", "Offline-classroom use (no wifi)",
     "1. Pre-cache app on lab machines\n2. Verify offline functionality complete",
     "Offline use viable",
     "Low-Medium", "Minor", "Manual", ""),
    ("Returning learner", "80", "Cold-start recovery after 6-month break",
     "1. Simulate long absence (manipulate localStorage timestamps)\n2. Open app\n3. Verify 'welcome back' + suggested resumption",
     "Smooth resumption",
     "Low-Medium", "Minor", "Manual", ""),
    ("Returning learner", "80", "SRS scheduling resilience to long gaps",
     "1. Simulate 30-day absence\n2. Verify SRS doesn't dump all-cards-due simultaneously",
     "Graceful catch-up mode",
     "Low-Medium", "Minor", "Manual", ""),
    ("Bilingual toggle user", "81", "Toggle persistence across sessions",
     "1. Set HI on session 1\n2. Open session 2 same browser\n3. Verify still HI",
     "Preference persists",
     "Low", "Minor", "Manual", ""),
    ("Mobile / emerging-market", "82", "Sub-2GB-RAM Android device performance",
     "1. Test on Android Go device\n2. Verify usable performance",
     "Usable on low-end Android",
     "Medium", "Major", "Manual", ""),
    ("Mobile / emerging-market", "82", "Intermittent-connectivity resilience",
     "1. Toggle network on/off during use\n2. Verify graceful sync + offline-fallback",
     "Intermittent-net usable",
     "Medium", "Major", "Manual", ""),
    ("Mobile / emerging-market", "82", "Data-quota efficiency (per-session MB transferred)",
     "1. Measure first-load + per-session network bytes\n2. Verify <10MB first-load, <1MB per subsequent session",
     "Data-light",
     "Medium", "Minor", "Auto", ""),
    ("Visually-impaired", "83", "Full app navigation via VoiceOver / NVDA",
     "1. Blind tester completes 1 vocab module via screen reader",
     "Completable via SR",
     "Medium", "Major", "Manual", ""),
    ("Visually-impaired", "83", "Furigana exposure to screen reader",
     "1. Verify ruby tags expose readings appropriately",
     "Furigana accessible",
     "Medium", "Major", "Manual", ""),
    ("Cognitively-diverse", "84", "ADHD-friendly pacing-control",
     "1. Verify learner can pause / skip / reduce stimulation",
     "Pacing control exists",
     "Low-Medium", "Minor", "Manual", ""),
    ("Cognitively-diverse", "84", "Dyslexia-friendly reading-flow",
     "1. Verify font / spacing / line-height are dyslexia-friendly defaults",
     "Dyslexia-friendly OR option exists",
     "Low", "Minor", "Manual", ""),
]

TABS = [
    ("A. Japanese language", "Native Japanese teacher, JLPT-N5 specialist, pitch-accent, TTS-reviewer, sociolinguist, translator, counter specialist, kanji specialist, romaji, furigana",
     A_JAPANESE),
    ("B. JLPT format", "JLPT exam-design, JEES-aligned, psychometrician, mock-exam timing specialists (perspectives 11-14)",
     B_JLPT_FORMAT),
    ("C. Hindi locale", "Native-Hindi reviewer, Hindi pedagogical terminology, Devanagari typography, Hindi register, EN↔HI bilingual (perspectives 15-19)",
     C_HINDI),
    ("D. UX design", "UI / UX designer, visual designer, interaction designer, IA, onboarding, cognitive-load, gamification, form-input, dark-mode (perspectives 20-28)",
     D_UX_DESIGN),
    ("E. Accessibility", "WCAG-AA reviewer, screen-reader (VoiceOver/NVDA/TalkBack), motor-impairment, cognitive-accessibility, hearing-impaired (perspectives 29-33)",
     E_ACCESSIBILITY),
    ("F. Security", "OWASP, CSP, supply-chain, secrets, penetration, GitHub Actions security (perspectives 34-39)",
     F_SECURITY),
    ("G. Privacy and legal", "Privacy/GDPR/DPDP, cookie-consent, COPPA, license-compliance, trademark, advertising-claims (perspectives 40-45)",
     G_PRIVACY_LEGAL),
    ("H. Performance", "Web-performance, audio-cache, PWA, cross-browser, mobile-responsive, font-rendering, i18n, SEO (perspectives 46-53)",
     H_PERFORMANCE),
    ("I. Data engineering", "Schema validation, schema versioning, CACHE_VERSION, backup, build/CI (perspectives 54-57)",
     I_DATA_ENG),
    ("J. Pedagogy", "SLA researcher, SRS algorithm, curriculum designer, assessment validity, comparative pedagogy, HI-L1 error anticipation (perspectives 58-63)",
     J_PEDAGOGY),
    ("K. QA testing", "Exploratory tester, automated testing, visual regression, localization testing, audio playback (perspectives 64-68)",
     K_QA),
    ("L. Cultural ethical", "Cultural-sensitivity (JA + HI), AI-ethics/disclosure, trust-and-safety (perspectives 69-72)",
     L_CULTURAL_ETHICAL),
    ("M. Operations", "DevOps/SRE, analytics, customer-support, documentation (perspectives 73-76)",
     M_OPERATIONS),
    ("N. End-user POV", "Primary-persona learner, self-study, classroom-instructor, returning-learner, bilingual-toggle, mobile/emerging-market, visually-impaired, cognitively-diverse (perspectives 77-84)",
     N_END_USER_POV),
]


def add_overview_tab(wb: Workbook) -> None:
    ws = wb.active
    ws.title = "Overview"
    ws["A1"] = "JLPT N5 Tutor — Test Scenarios by Specialist Perspective"
    ws["A1"].font = TITLE_FONT
    ws["A2"] = "Generated from the 84-perspective list (categories A–N). Each tab = one category."
    ws["A3"] = (
        "Writing-discipline note: every scenario phrasing is bounded — names "
        "exactly what is scanned/sampled. No claim implies universal coverage. "
        "A future JLPT exam, native reviewer, or institutional adopter may "
        "surface item classes outside what is captured here."
    )
    ws["A3"].alignment = WRAP
    ws.row_dimensions[3].height = 60
    ws.column_dimensions["A"].width = 28
    ws.column_dimensions["B"].width = 80
    ws.column_dimensions["C"].width = 14
    ws.column_dimensions["D"].width = 14

    headers = ["Tab", "Perspectives covered (with #)", "Scenario count", "Priority HIGH count"]
    for col, h in enumerate(headers, start=1):
        c = ws.cell(row=5, column=col, value=h)
        c.fill = HEADER_FILL
        c.font = HEADER_FONT
        c.alignment = WRAP

    row = 6
    total_scenarios = 0
    total_high = 0
    for tab_name, perspectives_desc, scenarios in TABS:
        count = len(scenarios)
        high = sum(1 for s in scenarios if s[5].lower() == "high")
        total_scenarios += count
        total_high += high
        ws.cell(row=row, column=1, value=tab_name).alignment = WRAP
        ws.cell(row=row, column=2, value=perspectives_desc).alignment = WRAP
        ws.cell(row=row, column=3, value=count).alignment = WRAP
        ws.cell(row=row, column=4, value=high).alignment = WRAP
        ws.row_dimensions[row].height = 50
        row += 1

    ws.cell(row=row, column=1, value="TOTAL").font = Font(bold=True)
    ws.cell(row=row, column=3, value=total_scenarios).font = Font(bold=True)
    ws.cell(row=row, column=4, value=total_high).font = Font(bold=True)


def add_scenario_tab(wb: Workbook, tab_name: str, perspectives_desc: str,
                     scenarios) -> None:
    ws = wb.create_sheet(title=tab_name[:31])  # Excel tab name limit
    ws["A1"] = tab_name
    ws["A1"].font = TITLE_FONT
    ws["A2"] = f"Perspectives: {perspectives_desc}"
    ws["A2"].alignment = WRAP
    ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=len(COLUMNS))
    ws.row_dimensions[2].height = 45

    # Header row at row 4
    for col, (h, width) in enumerate(COLUMNS, start=1):
        c = ws.cell(row=4, column=col, value=h)
        c.fill = HEADER_FILL
        c.font = HEADER_FONT
        c.alignment = WRAP
        ws.column_dimensions[get_column_letter(col)].width = width

    # Data rows
    prefix = tab_name.split(".")[0].strip()  # "A", "B", ...
    for i, (subcat, persp, scenario, steps, expected, priority, severity, ttype, notes) \
            in enumerate(scenarios, start=1):
        r = 4 + i
        sid = f"{prefix}-{i:03d}"
        values = [sid, subcat, persp, scenario, steps, expected, priority,
                  severity, ttype, notes]
        for col, val in enumerate(values, start=1):
            c = ws.cell(row=r, column=col, value=val)
            c.alignment = WRAP
        # Estimate row height by longest cell content (rough)
        max_len = max(len(str(v)) for v in values)
        ws.row_dimensions[r].height = max(30, min(140, max_len // 3))

    ws.freeze_panes = "A5"


def main() -> None:
    wb = Workbook()
    add_overview_tab(wb)
    for tab_name, perspectives_desc, scenarios in TABS:
        add_scenario_tab(wb, tab_name, perspectives_desc, scenarios)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    wb.save(OUTPUT)
    print(f"Wrote {OUTPUT}")
    print(f"Tabs: {len(TABS) + 1} (1 overview + {len(TABS)} category tabs)")
    print(f"Scenarios: {sum(len(s) for _, _, s in TABS)}")


if __name__ == "__main__":
    main()
