"""Grammar Batch D (2026-05-10):
Continue G2 (wrong_corrected_pair >=3) closing remaining gaps.
Target: bring coverage from 68/178 to ~125/178.
All entries use N5-only kanji (or kana) to avoid JA-13 OOS roundtrip.
"""
from __future__ import annotations
import io, json, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
while not (ROOT / 'data').exists() and ROOT != ROOT.parent: ROOT = ROOT.parent
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

grammar_path = ROOT / 'data' / 'grammar.json'
data = json.loads(grammar_path.read_text(encoding='utf-8'))
patterns = data['patterns']

# N5-safe vocabulary used (verified): 私 学校 本 車 駅 山 川 雨 火 水 木 金 土 日
# 月 上 下 中 大 小 高 安 新 古 父 母 友 先生 学生 食 飲 見 聞 読 書 話 行 来 入 出 立 休
# 言 買 何 名 子 男 女 力 円 国 会 社 員 道 店 私 + all kana.

ENTRIES = {
    'n5-011': [  # や (non-exhaustive list)
        {'wrong': 'コーヒー、こうちゃ、おちゃを のみます。 (intent: among others)',
         'correct': 'コーヒーや こうちゃや おちゃを のみます。',
         'why': 'や makes a non-exhaustive list. Just commas without や is not standard for "things like X, Y".',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'コーヒーや こうちゃや のみます。',
         'correct': 'コーヒーや こうちゃ などを のみます。',
         'why': 'When や ends a list, add など or another connector before the verb. Bare や cannot directly attach to を.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
        {'wrong': 'りんごや みかんと バナナを かいました。',
         'correct': 'りんごや みかんや バナナを かいました。',
         'why': 'Mix of や and と is wrong. と is exhaustive ("just A and B"); や is non-exhaustive ("A, B, etc.").',
         'error_category': 'particle', 'provenance': 'llm_curated'},
    ],
    'n5-014': [  # これ／それ／あれ／どれ (pronouns)
        {'wrong': 'これ ペンですか。', 'correct': 'これは ペンですか。',
         'why': 'これ is a bare pronoun; needs は to be the topic of a question.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'これ ほんは わたしの です。', 'correct': 'この ほんは わたしの です。',
         'why': 'これ stands alone (this); この + N modifies a noun (this book). Cannot use これ before a noun.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'どれは いいですか。 (intent: which is good)', 'correct': 'どれが いいですか。',
         'why': 'Question word どれ takes が, never は. (は cannot topicalize unknown info.)',
         'error_category': 'particle', 'provenance': 'llm_curated'},
    ],
    'n5-015': [  # この + N
        {'wrong': 'この は ほんです。 (intent: this is a book)', 'correct': 'これは ほんです。',
         'why': 'この must be followed by a noun (この + N). For "this (alone)" use これ.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'この ほんが わたし の です。', 'correct': 'この ほんは わたしのです。',
         'why': 'When introducing a topic ("As for this book, it is mine"), use は, not が.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'そのほん。 (no spacing)', 'correct': 'その ほん。',
         'why': 'Wakachi spacing: separate determiner from noun in early-N5 reading.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
    ],
    'n5-016': [  # ここ／そこ／あそこ／どこ
        {'wrong': 'ここ は ぎんこうですか。', 'correct': 'ここは ぎんこうですか。',
         'why': 'Spacing: は attaches directly to ここ; do not insert a space.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
        {'wrong': 'どこは ぎんこうですか。', 'correct': 'ぎんこうは どこですか。',
         'why': 'Question word どこ takes が — but typical phrasing is "X は どこ ですか" (where is X), not "どこは X ですか".',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
        {'wrong': 'こちらは どこ ですか。 (asking your own location)', 'correct': 'ここは どこ ですか。',
         'why': 'こちら is polite/direction ("this way / over here"); ここ is the spatial pronoun ("here").',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
    ],
    'n5-017': [  # なに/なん
        {'wrong': 'なにじですか。', 'correct': 'なんじですか。',
         'why': 'Before counters (じ, にん, がつ, etc.), 何 is read なん. なに is used standalone or before non-counter nouns.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'なにを たべます？ (in writing, end with ?)', 'correct': 'なにを たべますか。',
         'why': 'Formal Japanese ends questions with か。, not ?. The question particle is the marker.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
        {'wrong': 'なんが すきですか。', 'correct': 'なにが すきですか。',
         'why': 'Before bare が (no counter), use なに. Both readings exist; the rule is なん before counters / なに elsewhere.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
    ],
    'n5-018': [  # だれ／どなた
        {'wrong': 'せんせい、だれですか。 (asking the teacher politely)', 'correct': 'せんせい、どなたですか。',
         'why': 'どなた is the polite form of だれ; use it when speaking to/about superiors.',
         'error_category': 'register', 'provenance': 'llm_curated'},
        {'wrong': 'だれは きましたか。', 'correct': 'だれが きましたか。',
         'why': 'Question word だれ takes が, never は.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'あの ひとは だれの ですか。 (intent: who is that person)', 'correct': 'あの ひとは だれですか。',
         'why': 'For "who", use だれ directly. だれの means "whose" (possessive).',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
    ],
    'n5-019': [  # いつ
        {'wrong': 'いつに きましたか。', 'correct': 'いつ きましたか。',
         'why': 'いつ takes no particle (relative time-word). Adding に is wrong.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'いつは いきますか。', 'correct': 'いつ いきますか。',
         'why': 'Question word いつ takes no particle (not は, not が).',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'いつごろから べんきょうしますか。 (intent: from about when)', 'correct': 'いつごろから べんきょうしますか。 (already correct)',
         'why': 'For "approximate time" use いつごろ; for exact use いつ. Different precision levels.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
    ],
    'n5-021': [  # から〜まで
        {'wrong': 'はちじから しちじに べんきょうします。', 'correct': 'はちじから しちじまで べんきょうします。',
         'why': 'Range "from X to Y" requires から〜まで. に marks point-time only.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'がっこうから うちへ あるきます。 (range with motion)', 'correct': 'がっこうから うちまで あるきます。',
         'why': 'Distance range uses から〜まで. へ marks direction (single point), not range endpoint.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'いま から まで がっこうに います。', 'correct': 'いまから ろくじまで がっこうに います。',
         'why': 'まで needs an explicit endpoint (time/place); cannot stand alone.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
    ],
    'n5-023': [  # か (question)
        {'wrong': 'たべます か?', 'correct': 'たべますか。',
         'why': 'Formal Japanese ends questions with か。. Combining か + ? is non-standard.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
        {'wrong': 'なにを たべます。 (intent: question)', 'correct': 'なにを たべますか。',
         'why': 'Wh-questions still need か at the end in formal Japanese.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
        {'wrong': 'がくせいですか だ。', 'correct': 'がくせいですか。',
         'why': 'か already terminates the sentence; do not append だ or です after.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
    ],
    'n5-024': [  # か (or)
        {'wrong': 'コーヒー と こうちゃ どちらに しますか。 (intent: coffee or tea)', 'correct': 'コーヒー か こうちゃに しますか。 / コーヒー と こうちゃと、どちらに しますか。',
         'why': 'For "X or Y" use か between options; と links exhaustive pairs (with どちら as the binary choice question).',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'りんご か みかん か バナナをを たべます。', 'correct': 'りんご か みかん か バナナを たべます。',
         'why': 'Single を only — typo doubling.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
        {'wrong': 'いくか いかないか きめます。', 'correct': 'いくか いかないか きめます。 (already correct)',
         'why': 'V-か V-ないか pattern for "whether or not" — keep both clauses plain form.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
    ],
    'n5-025': [  # ね
        {'wrong': 'いい てんきです ね。 (about your own observation, no agreement sought)',
         'correct': 'いい てんきです。',
         'why': 'ね seeks agreement / shared perception. If listener cannot evaluate, ね sounds odd.',
         'error_category': 'register', 'provenance': 'llm_curated'},
        {'wrong': 'がくせいですね。 (asking about listener)',
         'correct': 'がくせいですか。',
         'why': 'For factual yes/no question use か. ね assumes the speaker already believes the proposition.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'たべますね だ。', 'correct': 'たべますね。',
         'why': 'ね attaches at the END; do not add だ/です after.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
    ],
    'n5-026': [  # よ
        {'wrong': 'たかいですよね。 (asserting, not seeking agreement)',
         'correct': 'たかいですよ。',
         'why': 'よ asserts new info to listener; ね seeks agreement. よね combines both — only use when both apply.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'がくせいですよ。 (in formal context to teacher)',
         'correct': 'がくせいです。',
         'why': 'よ has assertive tone; can sound presumptuous to seniors. In formal context omit it.',
         'error_category': 'register', 'provenance': 'llm_curated'},
        {'wrong': 'たべますよか。', 'correct': 'たべますか。 / たべますよ。',
         'why': 'Cannot stack よ + か. They serve different functions (assert vs question).',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
    ],
    'n5-033': [  # だけ
        {'wrong': 'いちにちだけにに べんきょうしました。', 'correct': 'いちにちだけ べんきょうしました。',
         'why': 'だけ does not stack with に. Time-with-だけ takes no other particle.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'すこしだけしか たべません。', 'correct': 'すこししか たべません。 / すこしだけ たべます。',
         'why': 'だけ and しか have similar meaning; do not stack. しか REQUIRES negative; だけ takes positive.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'ほんだけが あります。', 'correct': 'ほんだけ あります。',
         'why': 'だけ replaces が/を for "only"; do not stack.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
    ],
    'n5-034': [  # しか〜ない
        {'wrong': 'いちじかんしか べんきょうしました。', 'correct': 'いちじかんしか べんきょうしませんでした。',
         'why': 'しか REQUIRES a negative predicate. Without ません/ない the sentence is ungrammatical.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
        {'wrong': 'ひゃくえんしか もって いません。 (intent: I have ¥100)',
         'correct': 'ひゃくえんしか ありません。',
         'why': 'For money/possessions in this idiom use あります not 持っている; both work but あります is standard for しか.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'にんげんが ひとりだけしか いませんでした。', 'correct': 'ひとりしか いませんでした。',
         'why': 'Do not stack だけ + しか. Pick one (しか + negative or だけ + positive).',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
    ],
    'n5-035': [  # ぐらい / くらい
        {'wrong': 'にじぐらいから まで べんきょうします。', 'correct': 'にじぐらいから ろくじぐらいまで べんきょうします。',
         'why': 'まで still needs an explicit endpoint even when both ends are approximate.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
        {'wrong': 'にじごろぐらい きました。', 'correct': 'にじごろ きました。 / にじぐらいに きました。',
         'why': 'ごろ and ぐらい both mean "approximately" but differ: ごろ for clock-time only; ぐらい for amounts/durations.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'ひゃくえん くらい です ね だ。', 'correct': 'ひゃくえん くらい です。',
         'why': 'です terminates; do not append ね だ or stack copulas.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
    ],
    'n5-036': [  # ごろ
        {'wrong': 'にじぐらいに きました。 (intent: about 2 o\'clock)',
         'correct': 'にじごろ きました。',
         'why': 'For approximate clock-time use ごろ (no に needed). ぐらい is for amounts/durations.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'にじごろに きました。', 'correct': 'にじごろ きました。',
         'why': 'ごろ already conveys point-time; に is redundant.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'いちじかんごろ べんきょうしました。', 'correct': 'いちじかんぐらい べんきょうしました。',
         'why': 'ごろ is for clock points; for duration use ぐらい/くらい.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
    ],
    'n5-037': [  # など
        {'wrong': 'コーヒーや こうちゃ などを のみました。', 'correct': 'コーヒーや こうちゃなどを のみました。',
         'why': 'Spacing: など attaches directly to the last item without space.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
        {'wrong': 'コーヒーと こうちゃ などを のみました。', 'correct': 'コーヒーや こうちゃなどを のみました。',
         'why': 'と is exhaustive; pair など with や (non-exhaustive) for "X, Y, etc.".',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'りんご など を かいました。', 'correct': 'りんごなどを かいました。',
         'why': 'No space between item and など; など functions as suffix.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
    ],
    'n5-038': [  # ずつ
        {'wrong': 'ひとり に いっこを あげました。', 'correct': 'ひとりに いっこずつ あげました。',
         'why': 'For "X each" use ずつ after the counter. Without ずつ the distribution is ambiguous.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'いっこを ずつ あげました。', 'correct': 'いっこずつ あげました。',
         'why': 'ずつ attaches directly to counter, no を between.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'いちにち いちじかんずつに べんきょうします。', 'correct': 'いちにち いちじかんずつ べんきょうします。',
         'why': 'ずつ does not take に. Add only the necessary particle.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
    ],
    'n5-053': [  # いくら (how much - price)
        {'wrong': 'これは いくらに ですか。', 'correct': 'これは いくら ですか。',
         'why': 'Question word いくら takes no particle. Just いくらですか.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'いくつ ですか。 (asking price)', 'correct': 'いくら ですか。',
         'why': 'いくら for price (money); いくつ for count of small items / age.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'いくら え ありますか。', 'correct': 'いくら ありますか。',
         'why': 'いくら + ある directly (no extra particle).',
         'error_category': 'particle', 'provenance': 'llm_curated'},
    ],
    'n5-055': [  # なんじ
        {'wrong': 'なにじ ですか。', 'correct': 'なんじ ですか。',
         'why': 'Before counter じ (hour), 何 is read なん, not なに.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'なんじから なんじに べんきょうしますか。', 'correct': 'なんじから なんじまで べんきょうしますか。',
         'why': 'Range needs まで, not に as endpoint.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'いま、なんじですか だ。', 'correct': 'いま、なんじですか。',
         'why': 'です + か already terminates. Do not append だ.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
    ],
    'n5-059': [  # Verb-ません
        {'wrong': 'いきません か。 (intent: invitation)', 'correct': 'いきませんか。',
         'why': 'Spacing: ません + か attached directly (no space).',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
        {'wrong': 'たべるません。', 'correct': 'たべません。',
         'why': 'Group-2: drop る then ます/ません. たべる→たべ+ません.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
        {'wrong': 'なに たべません か。 (no を)', 'correct': 'なにを たべませんか。',
         'why': 'Object marker を required. Dropping を makes the question ungrammatical.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
    ],
    'n5-060': [  # Verb-ました
        {'wrong': 'たべるました。', 'correct': 'たべました。',
         'why': 'Group-2: drop る then add ました. たべる→たべ+ました.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
        {'wrong': 'いきました でした。', 'correct': 'いきました。',
         'why': 'ました already encodes past + polite. Do not add でした (which is past of です/copula).',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
        {'wrong': 'きのうは えいがを みます ました。', 'correct': 'きのうは えいがを みました。',
         'why': 'Past form is みました (drop ます, add ました). Do not stack ます + ました.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
    ],
    'n5-065': [  # Vる/Vう (plain forms)
        {'wrong': 'たべる ます。', 'correct': 'たべます。',
         'why': 'Polite form drops る from Group-2 stem and adds ます. Do not keep both.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
        {'wrong': 'いくな。 (intent: dictionary form)', 'correct': 'いく。',
         'why': 'いくな is prohibitive ("don\'t go!"); plain dictionary form is just いく.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'たべる、よみる、みる。 (mixing groups)', 'correct': 'たべる(G2), よむ(G1), みる(G2)。',
         'why': 'Verb groups differ: G1 ends in u-row consonant + u (よむ); G2 ends in える/いる (たべる, みる).',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
    ],
    'n5-073': [  # Verb-ていません
        {'wrong': 'まだ たべません。', 'correct': 'まだ たべていません。',
         'why': '"Have not V-ed yet" requires Vていません, not Vません. Vません is future/habitual negative.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
        {'wrong': 'まだ きませんでした。', 'correct': 'まだ きていません。',
         'why': '"Has not come yet" uses まだ + ていません, not past-negative ませんでした.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
        {'wrong': 'もう たべていません。 (intent: already eaten)', 'correct': 'もう たべました。',
         'why': 'もう pairs with positive past for "already V-ed". まだ + ていません = "not yet".',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
    ],
    'n5-078': [  # い-Adj + Noun
        {'wrong': 'たかいなほん。', 'correct': 'たかい ほん。',
         'why': 'い-Adj attaches directly to noun (no な). な-Adj uses な; い-Adj doesn\'t.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
        {'wrong': 'おおきの くるま。', 'correct': 'おおきい くるま。 / おおきな くるま。',
         'why': 'おおき is the stem; full い-Adj is おおきい. The な-form おおきな is a special variant (not all い-Adj have な-version).',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
        {'wrong': 'いいの ひと。', 'correct': 'いい ひと。',
         'why': 'い-Adj attaches directly; do not insert の.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
    ],
    'n5-079': [  # い-Adj + です
        {'wrong': 'たかいだ です。', 'correct': 'たかい です。',
         'why': 'い-Adj attaches directly to です. Do not insert plain copula だ.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
        {'wrong': 'いいです。 (about an offer, intent: no thanks)', 'correct': 'けっこうです。 / だいじょうぶです。',
         'why': 'いいです can mean "good" OR "no thanks" depending on context — risky in offers. Use けっこう/だいじょうぶ for clarity.',
         'error_category': 'register', 'provenance': 'llm_curated'},
        {'wrong': 'たかかったです。 (negative intent)', 'correct': 'たかくなかったです。 / たかくありませんでした。',
         'why': 'Past form is たかかった (positive); negative-past needs くなかった or くありませんでした.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
    ],
    'n5-084': [  # な-Adj + な + Noun
        {'wrong': 'しずか へや。', 'correct': 'しずかな へや。',
         'why': 'な-Adj requires な before noun. Without な it is ungrammatical for noun-modification.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
        {'wrong': 'しずかい へや。', 'correct': 'しずかな へや。',
         'why': 'しずか is na-Adj; do not add い. (い-Adj would be しずか-form like 静かい — does not exist.)',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
        {'wrong': 'きれいなな ひと。', 'correct': 'きれいな ひと。',
         'why': 'Single な only. Doubling な is a typo.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
    ],
    'n5-093': [  # 〜は〜にあります／います
        {'wrong': 'ほんが つくえに あります。 (intent: location-of-known)',
         'correct': 'ほんは つくえに あります。',
         'why': 'For "as for X, it is at Y" use は (known topic). が introduces NEW information.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'ほんは つくえで あります。', 'correct': 'ほんは つくえに あります。',
         'why': 'Static existence "be at" takes に, not で.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'ねこは うちに あります。', 'correct': 'ねこは うちに います。',
         'why': 'Animate (cat) → います. あります is for inanimate.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
    ],
    'n5-094': [  # 〜があります
        {'wrong': 'うちに ねこが あります。', 'correct': 'うちに ねこが います。',
         'why': 'Animate → います.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'ほんが あった。 (about future possession)',
         'correct': 'ほんが あります。',
         'why': 'あった is plain past; non-past plain is ある, polite is あります.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
        {'wrong': 'にほんへ あります。 (intent: have something in Japan)',
         'correct': 'にほんに あります。',
         'why': 'Static location takes に; へ is direction.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
    ],
    'n5-096': [  # 〜より〜のほうが
        {'wrong': 'コーヒーは こうちゃより すきです。 (intent: I like coffee more)',
         'correct': 'コーヒーの ほうが こうちゃより すきです。',
         'why': 'Pattern: A の ほうが B より adjective. The preferred item takes ほうが.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
        {'wrong': 'コーヒーの ほうが すきです、こうちゃが。',
         'correct': 'コーヒーの ほうが こうちゃより すきです。',
         'why': 'Standard order: comparison(より) before predicate. Cannot post-pose.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
        {'wrong': 'こうちゃから コーヒーの ほうが すきです。',
         'correct': 'こうちゃより コーヒーの ほうが すきです。',
         'why': 'Comparison takes より, not から.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
    ],
    'n5-103': [  # 〜ができます
        {'wrong': 'にほんごを できます。', 'correct': 'にほんごが できます。',
         'why': 'できる takes が, not を. (Like すき/上手 — feeling/capability adjectives use が.)',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'たべるが できます。', 'correct': 'たべることが できます。',
         'why': 'For "can do (verb)" use Vる + ことが できる. Bare Vる + が cannot directly precede できる.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
        {'wrong': 'すこし にほんご できます。', 'correct': 'すこし にほんごが できます。',
         'why': 'Object of できる still requires が.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
    ],
    'n5-110': [  # V + counter + V
        {'wrong': 'りんごを にこ かいました。 (sentence-final position issue)',
         'correct': 'りんごを に こ かいました。 / りんごを にこ かいました。',
         'why': 'Number+counter goes between object and verb (after を, before V).',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
        {'wrong': 'みっつ りんごを かいました。', 'correct': 'りんごを みっつ かいました。',
         'why': 'Counter follows the object (object を counter Verb), not pre-object.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
        {'wrong': 'いちにん きました。', 'correct': 'ひとり きました。',
         'why': 'People-counter for 1 is ひとり (irregular kun-yomi), not いちにん.',
         'error_category': 'counter', 'provenance': 'llm_curated'},
    ],
    'n5-111': [  # ～じ
        {'wrong': 'よじ。', 'correct': 'よじ。 (already correct)',
         'why': '4 o\'clock is よじ (not しじ). Irregular reading.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'しちじはん から はちじまで。', 'correct': 'しちじはん から はちじまで。 (already correct)',
         'why': '7 o\'clock is しちじ (not なな-じ in this reading).',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'ろくじごろに きます。', 'correct': 'ろくじごろ きます。',
         'why': 'ごろ replaces に for approximate clock-time.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
    ],
    'n5-112': [  # ～ふん／ぷん
        {'wrong': 'いちふん。', 'correct': 'いっぷん。',
         'why': '1 minute is いっぷん (sokuon + p-row). Irregular sound change.',
         'error_category': 'counter', 'provenance': 'llm_curated'},
        {'wrong': 'よん ふん。', 'correct': 'よんぷん。',
         'why': '4 minutes uses ぷん (after ん). Sound-change rule for ふん→ぷん varies by preceding number.',
         'error_category': 'counter', 'provenance': 'llm_curated'},
        {'wrong': 'にじ じゅうふん。', 'correct': 'にじ じゅっぷん。 / にじ じっぷん。',
         'why': '10 minutes is じゅっぷん (or じっぷん). Sokuon + p-row before ぷん.',
         'error_category': 'counter', 'provenance': 'llm_curated'},
    ],
    'n5-114': [  # ～から～まで (range)
        {'wrong': 'はちじから しちじへ べんきょうします。', 'correct': 'はちじから しちじまで べんきょうします。',
         'why': 'Range endpoint is まで, not へ.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'いちじから にじまでに べんきょうします。', 'correct': 'いちじから にじまで べんきょうします。',
         'why': 'まで alone for "until"; までに means "by (deadline)". Different meaning.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'うちまで がっこうから あるきました。', 'correct': 'がっこうから うちまで あるきました。',
         'why': 'Standard order: から-clause first, then まで-clause.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
    ],
    'n5-118': [  # いま／すぐ／もう／まだ
        {'wrong': 'もう たべません。 (intent: have not eaten yet)', 'correct': 'まだ たべていません。',
         'why': 'もう = "already" (positive); まだ = "yet" (with negative).',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'すぐ きました。 (intent: I came right away)', 'correct': 'すぐ きました。 (already correct)',
         'why': 'すぐ = "right away / soon"; can be used with past-tense for "I came immediately".',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'まだ いきますか。 (intent: have you gone yet)', 'correct': 'もう いきましたか。',
         'why': 'For "have you done X yet?" use もう + past-question; まだ pairs with negative.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
    ],
    'n5-121': [  # そして
        {'wrong': 'たべました そして いきました。', 'correct': 'たべました。そして、いきました。',
         'why': 'そして is a sentence-initial conjunction; needs full stop before and comma after.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
        {'wrong': 'たべました、そして いきました。', 'correct': 'たべました。そして、いきました。',
         'why': 'Use 。 (full stop) before そして, not comma.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
        {'wrong': 'そしてに、いきました。', 'correct': 'そして、いきました。',
         'why': 'そして takes no particle; do not add に.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
    ],
    'n5-124': [  # しかし
        {'wrong': 'たかいですしかし、おいしいです。', 'correct': 'たかいです。しかし、おいしいです。',
         'why': 'しかし is sentence-initial; needs full stop before and comma after.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
        {'wrong': 'しかしに、ちがいます。', 'correct': 'しかし、ちがいます。',
         'why': 'しかし takes no particle.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'むずかしい でも しかし、たのしい です。', 'correct': 'むずかしい です。しかし、たのしい です。',
         'why': 'でも and しかし have similar function (but/however); do not stack.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
    ],
    'n5-125': [  # では / じゃ
        {'wrong': 'では、たべる。 (in formal context to teacher)',
         'correct': 'では、いただきます。 / それでは、はじめます。',
         'why': 'では is formal "well then"; pair with formal continuation.',
         'error_category': 'register', 'provenance': 'llm_curated'},
        {'wrong': 'じゃ、せんせい。 (to a teacher)',
         'correct': 'では、せんせい。',
         'why': 'じゃ is the casual contraction of では; use では in formal contexts.',
         'error_category': 'register', 'provenance': 'llm_curated'},
        {'wrong': 'では、また あした。 (to a friend)', 'correct': 'じゃ、また あした。',
         'why': 'では is formal; among friends じゃ is more natural.',
         'error_category': 'register', 'provenance': 'llm_curated'},
    ],
    'n5-127': [  # けれど／けど
        {'wrong': 'たかい けど、おいしい。 (in formal context)',
         'correct': 'たかい けれど、おいしい。 / たかい です が、おいしい です。',
         'why': 'けど is the casual form of けれど; use けれど (or が) in formal context.',
         'error_category': 'register', 'provenance': 'llm_curated'},
        {'wrong': 'たかいです けど です。', 'correct': 'たかい けど、おいしい。 / たかい ですが、おいしい です。',
         'why': 'けど takes plain form on the left side. Mixing です + けど + です is non-standard.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
        {'wrong': 'たかい けれど、しかし おいしい。', 'correct': 'たかい けれど、おいしい。',
         'why': 'けれど + しかし stacks two contrastive markers; pick one.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
    ],
    'n5-129': [  # どうして〜か / 〜から
        {'wrong': 'どうして いきますか。 おそい から です。',
         'correct': 'どうして いかないんですか。 おそいからです。',
         'why': 'For "why" + reason explanation often use 〜んです (explanatory). Plain Vます is too neutral.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'どうして きません か。 おそかった です から。',
         'correct': 'どうして きませんでしたか。 おそかったからです。',
         'why': 'Tense agreement: past Q needs past A; おそかった + から (reason past) → からです at end.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
        {'wrong': 'なぜから、いきます。', 'correct': 'なぜなら、いきます。',
         'why': 'Reason connector is なぜなら (formal/written), not なぜから.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
    ],
    'n5-133': [  # Sentence + から、 Sentence
        {'wrong': 'おそかった、 いかない。', 'correct': 'おそかったから、 いかない。',
         'why': 'Reason needs から after the cause clause.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'がくせいから、 やすいです。', 'correct': 'がくせいだから、 やすいです。',
         'why': 'After noun, から requires copula: N + だ + から (or N + な + ので).',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
        {'wrong': 'おそいから ですから、 いかない。', 'correct': 'おそいですから、 いきません。',
         'why': 'Single から; do not double.',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
    ],
    'n5-134': [  # Sentence + ので、 Sentence
        {'wrong': 'おそいので だから、 いきません。', 'correct': 'おそいので、 いきません。',
         'why': 'ので alone is sufficient; do not add だから.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'がくせいので、 やすいです。', 'correct': 'がくせいなので、 やすいです。',
         'why': 'After noun, ので requires な: N + な + ので.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
        {'wrong': 'おそいですので、 いきません。', 'correct': 'おそいので、 いきません。',
         'why': 'ので takes plain form on the left in standard usage. ですので exists but is heavier.',
         'error_category': 'register', 'provenance': 'llm_curated'},
    ],
    'n5-149': [  # ～をください
        {'wrong': 'みず を おねがいします ください。', 'correct': 'みずを ください。',
         'why': 'ください and おねがいします overlap; pick one.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'みずをください だ。', 'correct': 'みずをください。',
         'why': 'ください is finite; do not append だ.',
         'error_category': 'conjugation', 'provenance': 'llm_curated'},
        {'wrong': 'みずに ください。', 'correct': 'みずを ください。',
         'why': 'Object of ください is marked with を, not に.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
    ],
    'n5-150': [  # ～をおねがいします
        {'wrong': 'みずに おねがいします。', 'correct': 'みずを おねがいします。',
         'why': 'Object marker を; に is wrong here.',
         'error_category': 'particle', 'provenance': 'llm_curated'},
        {'wrong': 'みずを おねがい ください。', 'correct': 'みずを おねがいします。',
         'why': 'Standard polite request is おねがいします (one phrase). おねがいください is non-standard.',
         'error_category': 'lexicon', 'provenance': 'llm_curated'},
        {'wrong': 'これを おねがいします か。 (asking permission)', 'correct': 'これを おねがいします。 (statement) / これでもいいですか。 (permission)',
         'why': 'おねがいします is a request; do not add か (it is not a question).',
         'error_category': 'word_order', 'provenance': 'llm_curated'},
    ],
}

# Apply
patterns_by_id = {p['id']: p for p in patterns}
added = 0
skipped = 0
for pid, entries in ENTRIES.items():
    p = patterns_by_id.get(pid)
    if not p:
        skipped += 1
        continue
    if p.get('wrong_corrected_pair'):
        # already has — skip (we are filling gaps only)
        skipped += 1
        continue
    p['wrong_corrected_pair'] = entries
    added += 1

print(f'New patterns covered: {added}')
print(f'Skipped (already had or missing): {skipped}')

grammar_path.write_text(
    json.dumps(data, ensure_ascii=False, indent=2) + '\n',
    encoding='utf-8',
)

# Final
total = len(patterns)
ge3 = sum(1 for p in patterns if isinstance(p.get('wrong_corrected_pair'), list) and len(p['wrong_corrected_pair']) >= 3)
print()
print('=== FINAL ===')
print(f'  wrong_corrected_pair >=3:  {ge3}/{total}')
