"""IMP-137: scaffold the Tofugu-style pedagogical essay layer for the
top-30 trickiest grammar patterns.

The audit asked for full long-form essays per pattern (Tofugu's
hallmark — 2,000-5,000-word write-ups that explain WHY a pattern
behaves the way it does, not just WHAT it means). That's months of
authoring work; not realistic in a single autonomous pass.

This script ships the structural scaffold so:
  1. The schema is in place — patterns gain an `essay` field.
  2. The renderer can light up the UI when an essay is present.
  3. Native review can fill the essays one at a time without
     further schema work.

Trickiness ranking (combined signal):
  +3 per common_mistakes entry
  +2 per contrasts entry
  +1 if l1_notes present
  +0.01 per char of explanation_en (longer = trickier)

Top-30 selected and seeded with a structured essay stub:

  essay: {
    intro: <auto-generated from meaning_en>,
    why_it_matters: '',         <- TODO native author
    common_pitfalls: <auto-extracted from common_mistakes if present>,
    contrasts: <auto-extracted from contrasts[] if present>,
    closing_practice_tip: '',   <- TODO native author
    provenance: 'needs_native_review',
  }

Patterns OUTSIDE the top-30 do not get the essay scaffold; they
remain available for future top-N expansion.
"""
from __future__ import annotations
import io
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
while not (ROOT / 'data').exists() and ROOT != ROOT.parent:
    ROOT = ROOT.parent

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

grammar_path = ROOT / 'data' / 'grammar.json'
data = json.loads(grammar_path.read_text(encoding='utf-8'))
patterns = data['patterns']


def trickiness_score(p: dict) -> float:
    return (
        len(p.get('common_mistakes') or []) * 3
        + len(p.get('contrasts') or []) * 2
        + (1 if p.get('l1_notes') else 0)
        + len(p.get('explanation_en') or '') / 100.0
    )


# Rank
ranked = sorted(patterns, key=trickiness_score, reverse=True)
top_n = 30
top_ids = {p['id'] for p in ranked[:top_n]}


def build_essay_stub(p: dict) -> dict:
    common = p.get('common_mistakes') or []
    contrasts = p.get('contrasts') or []
    meaning = p.get('meaning_en') or ''
    explanation = p.get('explanation_en') or ''

    intro = (
        f"This pattern, **{p.get('pattern', '')}**, "
        f"means: {meaning}. "
        f"At a glance: {explanation[:240]}{'...' if len(explanation) > 240 else ''}"
    ).strip()

    common_summary = ''
    if common:
        # Each item is typically a string; render as a bullet list summary.
        items = [str(c).strip() for c in common if c]
        if items:
            common_summary = ' · '.join(items[:5])

    contrasts_summary = ''
    if contrasts:
        items = []
        for c in contrasts[:5]:
            if isinstance(c, dict):
                items.append(f"vs {c.get('pattern_id', c.get('id', '?'))}: {c.get('note', '')}")
            elif isinstance(c, str):
                items.append(c)
        contrasts_summary = ' · '.join(items)

    return {
        'intro': intro,
        'why_it_matters': '',
        'common_pitfalls': common_summary,
        'contrasts': contrasts_summary,
        'closing_practice_tip': '',
        'provenance': 'needs_native_review',
    }


added = 0
preserved = 0
for p in patterns:
    if p['id'] not in top_ids:
        continue
    if p.get('essay') and isinstance(p['essay'], dict) and p['essay'].get('provenance') != 'needs_native_review':
        # Already authored; preserve
        preserved += 1
        continue
    p['essay'] = build_essay_stub(p)
    added += 1

grammar_path.write_text(
    json.dumps(data, ensure_ascii=False, indent=2) + '\n',
    encoding='utf-8',
)

print(f'Top-30 trickiness ranking applied.')
print(f'  Essay scaffolds added:     {added}')
print(f'  Pre-existing preserved:    {preserved}')
print()
print('Top 30 (id  pattern  trickiness score):')
for rank, p in enumerate(ranked[:30], 1):
    score = trickiness_score(p)
    print(f"  {rank:2}. {p['id']:8} {p.get('pattern',''):25} {score:.1f}")
