import*as d from"./storage.js";const s=10;function u(n){const e=n.length;let t=0,a=0,r=0;for(const c of n){const o=c.review_status;o==="native_reviewed"?t+=1:o==="llm_curated"?a+=1:o==="auto_generated"&&(r+=1)}const i=e>0?100*t/e:0;return{total:e,nativeReviewed:t,llmCurated:a,autoGenerated:r,percentNative:i,overThreshold:i>=s}}function v(n,e=!1){if(!l()||!e)return"";const t=n.review_status||"unknown",r={native_reviewed:{text:"Native-reviewed",cls:"badge-native"},llm_curated:{text:"AI-drafted",cls:"badge-llm"},auto_generated:{text:"Auto-generated",cls:"badge-auto"}}[t];return r?`<span class="provenance-badge ${r.cls}" title="${t}">${r.text}</span>`:""}function f(n,e){if(!l())return"";const t=Math.round(e.percentNative*10)/10;return`
    <p class="provenance-banner muted small">
      ${n}: ${e.nativeReviewed} of ${e.total} items native-reviewed
      (${t}% - threshold ${s}%).
    </p>
  `}function l(){try{return!!d.getSettings().showProvenanceBadges}catch{return!1}}const p={THRESHOLD_PERCENT:s};export{p as _internals,u as corpusProvenanceStats,f as renderCorpusBanner,v as renderItemBadge};
