import*as a from"./storage.js";const i="pwa.installDismissed";let n=null;function u(){"serviceWorker"in navigator&&location.protocol!=="file:"&&(document.readyState==="complete"?navigator.serviceWorker.register("./sw.js").catch(t=>{console.warn("Service worker registration failed:",t)}):window.addEventListener("load",()=>{navigator.serviceWorker.register("./sw.js").catch(t=>{console.warn("Service worker registration failed:",t)})})),window.addEventListener("beforeinstallprompt",t=>{t.preventDefault(),n=t,a.get(i,!1)||r()}),document.addEventListener("click",async t=>{if(t.target.closest("[data-trust-install]"))if(t.preventDefault(),n){n.prompt();const s=await n.userChoice;n=null,s&&s.outcome}else d()});const e=()=>{const t=l();t.hidden=navigator.onLine};window.addEventListener("online",e),window.addEventListener("offline",e),e(),"serviceWorker"in navigator&&navigator.serviceWorker.addEventListener("message",t=>{t.data?.type==="SW_UPDATE_AVAILABLE"&&c()})}function r(){if(document.getElementById("pwa-install-banner"))return;const e=document.createElement("div");e.id="pwa-install-banner",e.className="pwa-banner",e.setAttribute("role","region"),e.setAttribute("aria-label","Install this app"),e.innerHTML=`
    <span class="pwa-banner-copy">
      <strong>Install this app to use it offline from your home screen.</strong>
      <small class="pwa-banner-trust">No login. No tracking. No ads. Free, forever.</small>
    </span>
    <button id="pwa-install-yes" class="btn-primary">Install</button>
    <button id="pwa-install-no" class="btn-secondary">Not now</button>
  `,document.body.appendChild(e),document.getElementById("pwa-install-yes").addEventListener("click",async()=>{if(!n)return;n.prompt();const t=await n.userChoice;a.set(i,!0),n=null,e.remove()}),document.getElementById("pwa-install-no").addEventListener("click",()=>{a.set(i,!0),e.remove()})}function l(){let e=document.getElementById("offline-indicator");return e||(e=document.createElement("div"),e.id="offline-indicator",e.className="offline-indicator",e.setAttribute("role","status"),e.setAttribute("aria-live","polite"),e.textContent="Offline - cached content only",e.hidden=!0,document.body.appendChild(e),e)}function d(){const e=navigator.userAgent||"";let t;/iPhone|iPad|iPod/i.test(e)?t='iOS: tap the Share button in Safari, then "Add to Home Screen".':/Firefox/i.test(e)?t='Firefox: open the menu, then "Install" or "Add to Home Screen".':t='Look for an install / "Add to home screen" option in your browser menu.';const o=document.createElement("div");o.className="pwa-toast",o.setAttribute("role","status"),o.innerHTML=`<span>${t}</span><button class="btn-secondary" aria-label="Dismiss">\xD7</button>`,document.body.appendChild(o),o.querySelector("button").addEventListener("click",()=>o.remove()),setTimeout(()=>o.remove(),8e3)}function c(){if(document.getElementById("sw-update-toast"))return;const e=document.createElement("div");e.id="sw-update-toast",e.className="pwa-toast",e.setAttribute("role","status"),e.innerHTML=`
    <span>A new version is available.</span>
    <button id="sw-update-yes" class="btn-primary">Reload</button>
    <button id="sw-update-no" class="btn-secondary" aria-label="Dismiss">\xD7</button>
  `,document.body.appendChild(e),document.getElementById("sw-update-yes").addEventListener("click",()=>{navigator.serviceWorker.controller?.postMessage({type:"SKIP_WAITING"}),location.reload()}),document.getElementById("sw-update-no").addEventListener("click",()=>e.remove())}export{u as initPwa};
