let d=null,i=null,l=-1;async function f(){if(d)return d;try{const[n,r,s,t,a]=await Promise.all([fetch("data/grammar.json").then(e=>e.json()),fetch("data/vocab.json").then(e=>e.json()).catch(()=>({entries:[]})),fetch("data/kanji.json").then(e=>e.json()).catch(()=>({entries:[]})),fetch("data/reading.json").then(e=>e.json()).catch(()=>({passages:[]})),fetch("data/listening.json").then(e=>e.json()).catch(()=>({items:[]}))]);d={grammar:(n.patterns||[]).map(e=>({id:e.id,label:e.pattern,gloss:e.meaning_en||"",haystack:((e.id||"")+" "+(e.pattern||"")+" "+(e.meaning_en||"")+" "+(e.explanation_en||"")).toLowerCase()})),vocab:(r.entries||[]).slice(0,1500).map(e=>({id:e.form,label:e.form,gloss:e.gloss||"",reading:e.reading||"",haystack:((e.form||"")+" "+(e.reading||"")+" "+(e.gloss||"")).toLowerCase()})),kanji:(s.entries||[]).map(e=>({id:e.glyph,label:e.glyph,gloss:(e.meanings||[]).join(", "),haystack:((e.glyph||"")+" "+(e.on||[]).join(" ")+" "+(e.kun||[]).join(" ")+" "+(e.meanings||[]).join(" ")).toLowerCase()})),reading:(t.passages||[]).map(e=>({id:e.id,label:e.title_ja||e.id,gloss:e.level||"",haystack:((e.id||"")+" "+(e.title_ja||"")+" "+(e.ja||"")+" "+(e.topic||"")).toLowerCase()})),listening:(a.items||[]).map(e=>({id:e.id,label:e.title_ja||e.id,gloss:e.format_type||e.format||"",haystack:((e.id||"")+" "+(e.title_ja||"")+" "+(e.script_ja||"")+" "+(e.format||"")).toLowerCase()}))}}catch{d={grammar:[],vocab:[],kanji:[],reading:[],listening:[]}}return d}function p(n){const r=(n||"").trim().toLowerCase();if(!r)return{grammar:[],vocab:[],kanji:[],reading:[],listening:[]};const s=8,t=e=>e.filter(o=>o.haystack.includes(r)).slice(0,s),a=e=>{const o=new Set;return e.filter(c=>o.has(c.label)?!1:(o.add(c.label),!0))};return{grammar:t(d.grammar),vocab:a(t(d.vocab)),kanji:t(d.kanji),reading:t(d.reading||[]),listening:t(d.listening||[])}}const b={grammar:n=>`#/learn/${encodeURIComponent(n.id)}`,kanji:n=>`#/kanji/${encodeURIComponent(n.id)}`,vocab:n=>`#/learn/vocab/${encodeURIComponent(n.id)}`,reading:n=>`#/reading/${encodeURIComponent(n.id)}`,listening:n=>`#/listening/${encodeURIComponent(n.id)}`};function j(n){const r=n.grammar.length+n.vocab.length+n.kanji.length+(n.reading?.length||0)+(n.listening?.length||0);if(r===0)return'<p class="search-empty muted" role="status">No matches.</p>';let s=0;const t=(e,o)=>{const c=b[o](e),m=s++,h=o==="vocab"&&e.reading&&e.reading!==e.label?`<span lang="ja">${g(e.label)}</span> <span class="muted small" lang="ja">(${g(e.reading)})</span>`:`<span lang="ja">${g(e.label)}</span>`;return`
      <li><a href="${c}" data-idx="${m}" role="option">${h}${e.gloss?` <span class="muted small">- ${g(e.gloss)}</span>`:""}</a></li>
    `},a=(e,o,c)=>`
    <section class="search-group">
      <h4>${e} <span class="muted small">(${o.length})</span></h4>
      <ul>${o.map(m=>t(m,c)).join("")}</ul>
    </section>
  `;return`
    ${n.grammar.length?a("Grammar",n.grammar,"grammar"):""}
    ${n.kanji.length?a("Kanji",n.kanji,"kanji"):""}
    ${n.vocab.length?a("Vocab",n.vocab,"vocab"):""}
    ${n.reading?.length?a("Reading",n.reading,"reading"):""}
    ${n.listening?.length?a("Listening",n.listening,"listening"):""}
    <p class="search-status visually-hidden" aria-live="polite">${r} ${r===1?"result":"results"}.</p>
  `}function y(){return i||(i=document.createElement("div"),i.className="search-panel",i.hidden=!0,i.setAttribute("role","listbox"),i.setAttribute("aria-label","Search results"),document.body.appendChild(i),document.addEventListener("click",n=>{i.hidden||i.contains(n.target)||n.target.id!=="search-input"&&(i.hidden=!0,l=-1)}),i)}function k(n){const r=n.getBoundingClientRect(),s=document.documentElement.clientWidth,t=Math.min(320,s-24),a=Math.max(r.width,t),e=s-24,o=Math.min(a,e);let c=r.left+window.scrollX;c+o>window.scrollX+s-12&&(c=Math.max(window.scrollX+12,window.scrollX+s-o-12)),i.style.top=`${r.bottom+4+window.scrollY}px`,i.style.left=`${c}px`,i.style.width=`${o}px`}function u(n,r){n.forEach(s=>s.classList.remove("is-active")),r>=0&&r<n.length&&(n[r].classList.add("is-active"),n[r].scrollIntoView({block:"nearest"}))}async function w(){const n=document.getElementById("search-input");if(!n)return;y(),n.setAttribute("role","combobox"),n.setAttribute("aria-autocomplete","list"),n.setAttribute("aria-expanded","false");let r=!1;const s=async()=>{r||(await f(),r=!0)};n.addEventListener("focus",s),n.addEventListener("input",async()=>{await s();const t=n.value;if(!t.trim()){i.hidden=!0,n.setAttribute("aria-expanded","false"),l=-1;return}const a=p(t);i.innerHTML=j(a),k(n),i.hidden=!1,n.setAttribute("aria-expanded","true"),l=-1}),n.addEventListener("blur",()=>{setTimeout(()=>{i.matches(":hover")||(i.hidden=!0,n.setAttribute("aria-expanded","false"),l=-1)},150)}),n.addEventListener("keydown",t=>{if(t.key==="Escape"){n.value="",i.hidden=!0,n.setAttribute("aria-expanded","false"),l=-1,n.blur();return}if(i.hidden)return;const a=[...i.querySelectorAll("a[data-idx]")];a.length!==0&&(t.key==="ArrowDown"?(t.preventDefault(),l=(l+1)%a.length,u(a,l)):t.key==="ArrowUp"?(t.preventDefault(),l=l<=0?a.length-1:l-1,u(a,l)):t.key==="Enter"&&l>=0&&a[l]&&(t.preventDefault(),a[l].click()))}),document.addEventListener("keydown",t=>{const a=t.target;a&&(a.tagName==="INPUT"||a.tagName==="TEXTAREA"||a.isContentEditable)||t.key==="/"&&!t.metaKey&&!t.ctrlKey&&!t.altKey&&(t.preventDefault(),n.focus(),n.select())})}function g(n){return String(n??"").replace(/[&<>"']/g,r=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[r])}export{w as initSearch};
