// ISSUE-053 (audit round-6): provenance-badge UI scaffold.
//
// Q21 launch policy: ≥10% of items in any single corpus must be
// `native_reviewed` before the badge UI ships for that corpus. This
// module provides the infrastructure pre-wired behind a feature flag
// (`storage.settings.showProvenanceBadges`, default false). When a
// reviewer pass crosses the threshold, flip the flag - no rewriting
// from scratch.
//
// Reads the existing review_status / meanings_provenance / gloss_provenance
// fields written by tools/fix_imp_047_kanji_meanings_translate_*.py and
// tools/fix_imp_046_vocab_glosses_translate_*.py.

import * as storage from './storage.js';

const THRESHOLD_PERCENT = 10;

// Compute per-corpus native-reviewed share. `corpus` is an array of
// items each with `review_status` (closed enum). Returns:
//   { total, nativeReviewed, llmCurated, autoGenerated, percentNative,
//     overThreshold }
export function corpusProvenanceStats(corpus) {
  const total = corpus.length;
  let nr = 0, lc = 0, ag = 0;
  for (const item of corpus) {
    const rs = item.review_status;
    if (rs === 'native_reviewed') nr += 1;
    else if (rs === 'llm_curated') lc += 1;
    else if (rs === 'auto_generated') ag += 1;
  }
  const percentNative = total > 0 ? (100 * nr) / total : 0;
  return {
    total,
    nativeReviewed: nr,
    llmCurated:     lc,
    autoGenerated:  ag,
    percentNative,
    overThreshold:  percentNative >= THRESHOLD_PERCENT,
  };
}

// Render a small inline badge for a single item, given its review_status.
// Returns HTML string. Returns empty string when the feature flag is off
// OR the corpus the item belongs to hasn't yet crossed the threshold.
export function renderItemBadge(item, corpusOverThreshold = false) {
  if (!_isEnabled()) return '';
  if (!corpusOverThreshold) return '';
  const rs = item.review_status || 'unknown';
  const labels = {
    native_reviewed: { text: 'Native-reviewed', cls: 'badge-native' },
    llm_curated:     { text: 'AI-drafted',     cls: 'badge-llm'    },
    auto_generated:  { text: 'Auto-generated', cls: 'badge-auto'   },
  };
  const m = labels[rs];
  if (!m) return '';
  return `<span class="provenance-badge ${m.cls}" title="${rs}">${m.text}</span>`;
}

// Render a per-corpus summary banner (e.g., "12% of vocab native-reviewed").
// Useful for an admin / reviewer dashboard. Off when flag is off.
export function renderCorpusBanner(corpusName, stats) {
  if (!_isEnabled()) return '';
  const pct = Math.round(stats.percentNative * 10) / 10;
  return `
    <p class="provenance-banner muted small">
      ${corpusName}: ${stats.nativeReviewed} of ${stats.total} items native-reviewed
      (${pct}% - threshold ${THRESHOLD_PERCENT}%).
    </p>
  `;
}

function _isEnabled() {
  try {
    return !!storage.getSettings().showProvenanceBadges;
  } catch {
    return false;
  }
}

// Convenience for tests + tools.
export const _internals = { THRESHOLD_PERCENT };
