// ISSUE-053 (audit round-6): provenance-badge UI scaffold.
//
// BUG-012 (2026-05-16): the field value formerly `native_reviewed`
// is now `ai_quality_reviewed`. The label text presented to the user
// is "AI quality-reviewed" — NOT "Native-reviewed" — because the
// review-status assignment was done by Claude acting as a
// native-reviewer persona, not by an actual native human teacher.
// A future human-native review pass would introduce a separate
// `human_native_reviewed` value and badge.
//
// Q21 launch policy: ≥10% of items in any single corpus must be
// `ai_quality_reviewed` before the badge UI ships for that corpus.
// This module provides the infrastructure pre-wired behind a feature
// flag (`storage.settings.showProvenanceBadges`, default false). When
// a reviewer pass crosses the threshold, flip the flag - no rewriting
// from scratch.
//
// Reads the existing review_status / review_status_provenance /
// meanings_provenance / gloss_provenance fields written by the
// corpus-authoring tools and BUG-012's migration script.

import * as storage from './storage.js';

const THRESHOLD_PERCENT = 10;

// Compute per-corpus ai-quality-reviewed share. `corpus` is an array
// of items each with `review_status` (closed enum). Returns:
//   { total, aiQualityReviewed, llmCurated, autoGenerated,
//     percentAiQualityReviewed, overThreshold }
export function corpusProvenanceStats(corpus) {
  const total = corpus.length;
  let aiq = 0, lc = 0, ag = 0;
  for (const item of corpus) {
    const rs = item.review_status;
    // BUG-012: accept both the new value and the legacy value during
    // the migration window so a partially-migrated corpus doesn't
    // suddenly drop to 0% in the badge UI.
    if (rs === 'ai_quality_reviewed' || rs === 'native_reviewed') aiq += 1;
    else if (rs === 'llm_curated') lc += 1;
    else if (rs === 'auto_generated') ag += 1;
  }
  const percentAiQualityReviewed = total > 0 ? (100 * aiq) / total : 0;
  return {
    total,
    aiQualityReviewed: aiq,
    // Legacy alias for any older callers that still read `nativeReviewed`.
    nativeReviewed: aiq,
    llmCurated:     lc,
    autoGenerated:  ag,
    percentAiQualityReviewed,
    // Legacy alias.
    percentNative:  percentAiQualityReviewed,
    overThreshold:  percentAiQualityReviewed >= THRESHOLD_PERCENT,
  };
}

// Render a small inline badge for a single item, given its review_status.
// Returns HTML string. Returns empty string when the feature flag is off
// OR the corpus the item belongs to hasn't yet crossed the threshold.
export function renderItemBadge(item, corpusOverThreshold = false) {
  if (!_isEnabled()) return '';
  if (!corpusOverThreshold) return '';
  const rs = item.review_status || 'unknown';
  const labels = {
    ai_quality_reviewed: { text: 'AI quality-reviewed', cls: 'badge-ai-quality' },
    // Legacy value during migration window; presents the same label
    // so a partially-migrated corpus has consistent UI.
    native_reviewed:     { text: 'AI quality-reviewed', cls: 'badge-ai-quality' },
    llm_curated:         { text: 'AI-drafted',          cls: 'badge-llm'        },
    auto_generated:      { text: 'Auto-generated',      cls: 'badge-auto'       },
  };
  const m = labels[rs];
  if (!m) return '';
  return `<span class="provenance-badge ${m.cls}" title="${rs}">${m.text}</span>`;
}

// Render a per-corpus summary banner. Useful for an admin / reviewer
// dashboard. Off when flag is off.
export function renderCorpusBanner(corpusName, stats) {
  if (!_isEnabled()) return '';
  const pct = Math.round(stats.percentAiQualityReviewed * 10) / 10;
  return `
    <p class="provenance-banner muted small">
      ${corpusName}: ${stats.aiQualityReviewed} of ${stats.total} items AI-quality-reviewed
      (${pct}% - threshold ${THRESHOLD_PERCENT}%).
    </p>
  `;
}

function _isEnabled() {
  try {
    return !!storage.getSettings().showProvenanceBadges;
  } catch {
    return false;
  }
}

// Convenience for tests + tools.
export const _internals = { THRESHOLD_PERCENT };
